export interface BuiltinSound {
	id: number;
	name: string;
	description: string;
	url: string;
	previewUrl: string;
	downloadUrl: string;
	duration: number;
	filesize: number;
	type: string;
	channels: number;
	bitrate: number;
	bitdepth: number;
	samplerate: number;
	username: string;
	tags: string[];
	license: string;
	created: string;
	downloads: number;
	rating: number;
	ratingCount: number;
	category?: string;
	artist?: string;
}

// 1. SOUND EFFECTS (短促音效库)
// 说明：音效文件均托管于 Wikimedia Commons（永久、稳定、免费 CC 许可），
// 通过 upload.wikimedia.org 直接播放，无需 API Key。
export const BUILTIN_SOUNDS: BuiltinSound[] = [
	{
		id: 1001,
		name: "鸟鸣声 (Bird Chirping)",
		description: "Clear short bird chirp sound for nature videos and ambient scenes",
		url: "https://commons.wikimedia.org/wiki/File:Bird_chirp_2_(Gravity_Sound).mp3",
		previewUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Bird_chirp_2_%28Gravity_Sound%29.mp3",
		downloadUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Bird_chirp_2_%28Gravity_Sound%29.mp3",
		duration: 1.1,
		filesize: 12723,
		type: "mp3",
		channels: 1,
		bitrate: 128,
		bitdepth: 16,
		samplerate: 44100,
		username: "Gravity Sound",
		tags: ["birds", "chirp", "nature", "ambient", "鸟鸣", "自然", "环境音", "sound-effect"],
		license: "CC BY 4.0",
		created: "2024-01-01",
		downloads: 28000,
		rating: 4.8,
		ratingCount: 1200,
	},
	{
		id: 1002,
		name: "相机快门声 (Camera Shutter)",
		description: "Realistic DSLR camera shutter burst sound effect for photo and vlog moments",
		url: "https://commons.wikimedia.org/wiki/File:D7100_shot_sound_at_Continous_High(7fps).wav",
		previewUrl: "https://upload.wikimedia.org/wikipedia/commons/7/74/D7100_shot_sound_at_Continous_High%287fps%29.wav",
		downloadUrl: "https://upload.wikimedia.org/wikipedia/commons/7/74/D7100_shot_sound_at_Continous_High%287fps%29.wav",
		duration: 13.4,
		filesize: 2363818,
		type: "wav",
		channels: 1,
		bitrate: 1411,
		bitdepth: 16,
		samplerate: 44100,
		username: "Wikimedia Commons",
		tags: ["camera", "shutter", "photo", "snapshot", "click", "相机", "快门", "拍照", "sound-effect"],
		license: "CC BY-SA 3.0",
		created: "2024-01-02",
		downloads: 16800,
		rating: 4.7,
		ratingCount: 750,
	},
	{
		id: 1003,
		name: "人群笑声 (Laughter Crowd)",
		description: "Natural crowd laughing sound for reaction and fun moments",
		url: "https://commons.wikimedia.org/wiki/File:72843_lonemonk_approx-800-laughter-only-1.wav",
		previewUrl: "https://upload.wikimedia.org/wikipedia/commons/5/55/72843_lonemonk_approx-800-laughter-only-1.wav",
		downloadUrl: "https://upload.wikimedia.org/wikipedia/commons/5/55/72843_lonemonk_approx-800-laughter-only-1.wav",
		duration: 13.8,
		filesize: 2433248,
		type: "wav",
		channels: 2,
		bitrate: 1411,
		bitdepth: 16,
		samplerate: 44100,
		username: "LoneMonk",
		tags: ["laugh", "crowd", "fun", "reaction", "笑声", "人群", "欢乐", "反应", "sound-effect"],
		license: "CC BY 3.0",
		created: "2024-01-03",
		downloads: 21000,
		rating: 4.8,
		ratingCount: 890,
	},
	{
		id: 1004,
		name: "掌声 (Applause Clapping)",
		description: "Audience clapping and applause sound for show and celebration scenes",
		url: "https://commons.wikimedia.org/wiki/File:619016_mrrap4food_clapping-then-leaving.mp3",
		previewUrl: "https://upload.wikimedia.org/wikipedia/commons/0/02/619016_mrrap4food_clapping-then-leaving.mp3",
		downloadUrl: "https://upload.wikimedia.org/wikipedia/commons/0/02/619016_mrrap4food_clapping-then-leaving.mp3",
		duration: 28.7,
		filesize: 345511,
		type: "mp3",
		channels: 2,
		bitrate: 96,
		bitdepth: 16,
		samplerate: 44100,
		username: "mrrap4food",
		tags: ["applause", "clap", "crowd", "celebration", "掌声", "鼓掌", "庆祝", "观众", "sound-effect"],
		license: "CC0",
		created: "2024-01-04",
		downloads: 24000,
		rating: 4.9,
		ratingCount: 1100,
	},
	{
		id: 1005,
		name: "键盘打字声 (Keyboard Typing)",
		description: "Tactile mechanical keyboard typing sound for coding and tech videos",
		url: "https://commons.wikimedia.org/wiki/File:Typing_on_Keychron_V1_Ultra_(Red_Linear_Switch).wav",
		previewUrl: "https://upload.wikimedia.org/wikipedia/commons/2/27/Typing_on_Keychron_V1_Ultra_%28Red_Linear_Switch%29.wav",
		downloadUrl: "https://upload.wikimedia.org/wikipedia/commons/2/27/Typing_on_Keychron_V1_Ultra_%28Red_Linear_Switch%29.wav",
		duration: 17.7,
		filesize: 3406832,
		type: "wav",
		channels: 2,
		bitrate: 1536,
		bitdepth: 16,
		samplerate: 48000,
		username: "C40115",
		tags: ["keyboard", "typing", "mechanical", "clicks", "tech", "键盘", "打字", "敲击", "科技", "sound-effect"],
		license: "CC BY 4.0",
		created: "2024-01-05",
		downloads: 32000,
		rating: 4.9,
		ratingCount: 1100,
	},
	{
		id: 1006,
		name: "闹钟铃声 (Alarm Clock Beep)",
		description: "Computer generated beep alarm clock sound for alerts and wake-up scenes",
		url: "https://commons.wikimedia.org/wiki/File:Beep_alarm_clock.ogg",
		previewUrl: "https://upload.wikimedia.org/wikipedia/commons/4/42/Beep_alarm_clock.ogg",
		downloadUrl: "https://upload.wikimedia.org/wikipedia/commons/4/42/Beep_alarm_clock.ogg",
		duration: 6.1,
		filesize: 49536,
		type: "ogg",
		channels: 2,
		bitrate: 65,
		bitdepth: 16,
		samplerate: 44100,
		username: "Jeuwre",
		tags: ["alarm", "beep", "clock", "notification", "alert", "闹钟", "铃声", "提示", "提醒", "sound-effect"],
		license: "CC BY-SA 4.0",
		created: "2024-01-06",
		downloads: 18000,
		rating: 4.6,
		ratingCount: 640,
	},
	{
		id: 1007,
		name: "收银机声响 (Cash Register Coin)",
		description: "Classic cash register 'cha-ching' coin sound for rewards and money moments",
		url: "https://commons.wikimedia.org/wiki/File:Cha_Ching_Register-Muska666-173262285.wav",
		previewUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0b/Cha_Ching_Register-Muska666-173262285.wav",
		downloadUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0b/Cha_Ching_Register-Muska666-173262285.wav",
		duration: 2.1,
		filesize: 368650,
		type: "wav",
		channels: 2,
		bitrate: 1411,
		bitdepth: 16,
		samplerate: 44100,
		username: "Muska666",
		tags: ["coin", "cash", "register", "money", "reward", "金币", "收银", "金钱", "奖励", "sound-effect"],
		license: "CC BY-SA 4.0",
		created: "2024-01-07",
		downloads: 19500,
		rating: 4.8,
		ratingCount: 830,
	},
	{
		id: 1008,
		name: "教堂钟声 (Church Bell Ringing)",
		description: "Deep church bell ringing sound for solemn and classic scenes",
		url: "https://commons.wikimedia.org/wiki/File:Chorz%C3%B3w_Assumption_church_bell_ringing_2022.wav",
		previewUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Chorz%C3%B3w_Assumption_church_bell_ringing_2022.wav",
		downloadUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Chorz%C3%B3w_Assumption_church_bell_ringing_2022.wav",
		duration: 30.7,
		filesize: 5898284,
		type: "wav",
		channels: 2,
		bitrate: 1536,
		bitdepth: 16,
		samplerate: 48000,
		username: "Wikimedia Commons",
		tags: ["bell", "church", "ringing", "solemn", "classic", "钟声", "教堂", "庄重", "古典", "sound-effect"],
		license: "CC BY-SA 4.0",
		created: "2024-01-08",
		downloads: 16000,
		rating: 4.7,
		ratingCount: 580,
	},
	{
		id: 1009,
		name: "脚步声 (Footstep on Gravel)",
		description: "Crisp footstep on gravel sound for walking and outdoor scenes",
		url: "https://commons.wikimedia.org/wiki/File:Footstep_on_Gravel_(Gravity_Sound).mp3",
		previewUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f7/Footstep_on_Gravel_%28Gravity_Sound%29.mp3",
		downloadUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f7/Footstep_on_Gravel_%28Gravity_Sound%29.mp3",
		duration: 0.6,
		filesize: 12142,
		type: "mp3",
		channels: 1,
		bitrate: 128,
		bitdepth: 16,
		samplerate: 44100,
		username: "Gravity Sound",
		tags: ["footstep", "walk", "gravel", "outdoor", "脚步", "走路", "户外", "声音", "sound-effect"],
		license: "CC BY 4.0",
		created: "2024-01-09",
		downloads: 14800,
		rating: 4.6,
		ratingCount: 520,
	},
	{
		id: 1010,
		name: "风声与雪 (Wind and Snow)",
		description: "Atmospheric wind blowing through snow sound for winter and moody scenes",
		url: "https://commons.wikimedia.org/wiki/File:20221229_-_Abisko_Turiststation_at_night_-_Wind_and_snow.wav",
		previewUrl: "https://upload.wikimedia.org/wikipedia/commons/1/11/20221229_-_Abisko_Turiststation_at_night_-_Wind_and_snow.wav",
		downloadUrl: "https://upload.wikimedia.org/wikipedia/commons/1/11/20221229_-_Abisko_Turiststation_at_night_-_Wind_and_snow.wav",
		duration: 44.1,
		filesize: 7774108,
		type: "wav",
		channels: 2,
		bitrate: 1411,
		bitdepth: 16,
		samplerate: 44100,
		username: "Wikimedia Commons",
		tags: ["wind", "snow", "winter", "ambient", "atmosphere", "风声", "雪", "冬天", "环境音", "意境", "sound-effect"],
		license: "CC BY-SA 4.0",
		created: "2024-01-10",
		downloads: 20000,
		rating: 4.8,
		ratingCount: 720,
	},
	{
		id: 1011,
		name: "海浪声 (Ocean Waves)",
		description: "Relaxing ocean wave sound for beach, travel and meditation videos",
		url: "https://commons.wikimedia.org/wiki/File:Life_on_the_Ocean_Wave.wav",
		previewUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Life_on_the_Ocean_Wave.wav",
		downloadUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Life_on_the_Ocean_Wave.wav",
		duration: 57.9,
		filesize: 11125560,
		type: "wav",
		channels: 2,
		bitrate: 1536,
		bitdepth: 16,
		samplerate: 48000,
		username: "Wikimedia Commons",
		tags: ["ocean", "wave", "beach", "sea", "relax", "海浪", "大海", "海滩", "放松", "环境音", "sound-effect"],
		license: "Public Domain",
		created: "2024-01-11",
		downloads: 26000,
		rating: 4.9,
		ratingCount: 1050,
	},
	{
		id: 1012,
		name: "雨声 (Rain Ambience)",
		description: "Heavy loop raindrops ambience for rainy scenes and background noise",
		url: "https://commons.wikimedia.org/wiki/File:Listening_to_Raindrops_(1035382_-_heavy_loop).mp3",
		previewUrl: "https://upload.wikimedia.org/wikipedia/commons/5/56/Listening_to_Raindrops_%281035382_-_heavy_loop%29.mp3",
		downloadUrl: "https://upload.wikimedia.org/wikipedia/commons/5/56/Listening_to_Raindrops_%281035382_-_heavy_loop%29.mp3",
		duration: 30.0,
		filesize: 360263,
		type: "mp3",
		channels: 2,
		bitrate: 96,
		bitdepth: 16,
		samplerate: 44100,
		username: "Wikimedia Commons",
		tags: ["rain", "raindrop", "weather", "ambient", "雨声", "下雨", "天气", "环境音", "背景", "sound-effect"],
		license: "Public Domain",
		created: "2024-01-12",
		downloads: 30000,
		rating: 4.9,
		ratingCount: 1300,
	},
];

// 2. BACKGROUND MUSIC / SONGS (精选背景音乐与完整配乐)
// 说明：2002/2005/2006/2007 曲目托管于 Wikimedia Commons（公有领域或 CC 许可，永久稳定），
// 其余来自 Pixabay Free License 下载直链。
export const BUILTIN_MUSIC_TRACKS: BuiltinSound[] = [
	{
		id: 2001,
		name: "阳光微风 Vlog (Sunny Day Acoustic Pop)",
		description: "Upbeat and happy acoustic guitar pop background music for travel vlogs and lifestyle videos",
		url: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3",
		previewUrl: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3",
		downloadUrl: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3",
		duration: 135,
		filesize: 3200000,
		type: "mp3",
		channels: 2,
		bitrate: 320,
		bitdepth: 16,
		samplerate: 44100,
		username: "MusicTown",
		artist: "SunnyVlog Studio",
		category: "vlog",
		tags: ["vlog", "pop", "acoustic", "happy", "summer", "sunny", "阳光", "轻松", "欢快", "日常", "吉他"],
		license: "Pixabay Free License",
		created: "2024-01-01",
		downloads: 45000,
		rating: 4.9,
		ratingCount: 1820,
	},
	{
		id: 2002,
		name: "贝多芬悲怆奏鸣曲 (Beethoven Pathetique Sonata)",
		description: "Emotional classical piano sonata by Beethoven for storytelling, memories and romantic moments",
		url: "https://commons.wikimedia.org/wiki/File:Piano_Sonata_No.8,_Op.13_%E2%80%93_Ludwig_Van_Beethoven.oga",
		previewUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2e/Piano_Sonata_No.8%2C_Op.13_%E2%80%93_Ludwig_Van_Beethoven.oga",
		downloadUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2e/Piano_Sonata_No.8%2C_Op.13_%E2%80%93_Ludwig_Van_Beethoven.oga",
		duration: 120,
		filesize: 15951503,
		type: "oga",
		channels: 2,
		bitrate: 128,
		bitdepth: 16,
		samplerate: 44100,
		username: "Omega13a",
		artist: "Ludwig van Beethoven",
		category: "piano",
		tags: ["piano", "classical", "beethoven", "emotional", "cinematic", "钢琴", "古典", "贝多芬", "唯美", "抒情"],
		license: "CC BY 4.0",
		created: "2024-01-05",
		downloads: 58000,
		rating: 5.0,
		ratingCount: 2400,
	},
	{
		id: 2003,
		name: "午后咖啡 Lofi 节拍 (Chill Lofi Hip Hop)",
		description: "Cozy relaxing lo-fi hip hop beat with warm rhodes electric piano for coding and study",
		url: "https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3",
		previewUrl: "https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3",
		downloadUrl: "https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3",
		duration: 142,
		filesize: 3400000,
		type: "mp3",
		channels: 2,
		bitrate: 320,
		bitdepth: 16,
		samplerate: 44100,
		username: "LofiBeatMaker",
		artist: "Coffee Break",
		category: "lofi",
		tags: ["lofi", "chill", "hiphop", "relax", "study", "beats", "节奏", "咖啡", "学习", "办公", "放松"],
		license: "Pixabay Free License",
		created: "2024-01-10",
		downloads: 62000,
		rating: 4.9,
		ratingCount: 3100,
	},
	{
		id: 2004,
		name: "科技脉动电子乐 (Cyberpulse Electronic Drive)",
		description: "Modern futuristic synthwave electronic track with driving beats for tech intros and gaming",
		url: "https://cdn.pixabay.com/download/audio/2022/10/14/audio_9939f792cb.mp3",
		previewUrl: "https://cdn.pixabay.com/download/audio/2022/10/14/audio_9939f792cb.mp3",
		downloadUrl: "https://cdn.pixabay.com/download/audio/2022/10/14/audio_9939f792cb.mp3",
		duration: 130,
		filesize: 3100000,
		type: "mp3",
		channels: 2,
		bitrate: 320,
		bitdepth: 16,
		samplerate: 44100,
		username: "SynthLab",
		artist: "CyberDrive",
		category: "electronic",
		tags: ["electronic", "synthwave", "tech", "futuristic", "gaming", "科技", "电音", "动感", "游戏", "快节奏"],
		license: "Pixabay Free License",
		created: "2024-01-15",
		downloads: 41000,
		rating: 4.8,
		ratingCount: 1650,
	},
	{
		id: 2005,
		name: "莫扎特第四十交响曲 (Mozart Symphony No.40)",
		description: "Powerful orchestral symphony by Mozart with strings and drama for trailers and epic scenes",
		url: "https://commons.wikimedia.org/wiki/File:Mozart_-_Symphony_No._40_in_G_minor,_K550_-_I._Molto_allegro_(Musopen_Symphony).flac",
		previewUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a8/Mozart_-_Symphony_No._40_in_G_minor%2C_K550_-_I._Molto_allegro_%28Musopen_Symphony%29.flac",
		downloadUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a8/Mozart_-_Symphony_No._40_in_G_minor%2C_K550_-_I._Molto_allegro_%28Musopen_Symphony%29.flac",
		duration: 120,
		filesize: 65272320,
		type: "flac",
		channels: 2,
		bitrate: 1411,
		bitdepth: 16,
		samplerate: 44100,
		username: "Musopen Symphony",
		artist: "Wolfgang Amadeus Mozart",
		category: "epic",
		tags: ["epic", "classical", "orchestral", "mozart", "cinematic", "古典", "交响", "莫扎特", "史诗", "震撼"],
		license: "Public Domain",
		created: "2024-01-20",
		downloads: 52000,
		rating: 5.0,
		ratingCount: 2900,
	},
	{
		id: 2006,
		name: "二胡独奏江河水流 (Erhu Solo River)",
		description: "Traditional Chinese erhu instrumental solo for cultural and scenic videos",
		url: "https://commons.wikimedia.org/wiki/File:%E6%B1%9F%E6%B2%B3%E6%B0%B4.ogg",
		previewUrl: "https://upload.wikimedia.org/wikipedia/commons/3/30/%E6%B1%9F%E6%B2%B3%E6%B0%B4.ogg",
		downloadUrl: "https://upload.wikimedia.org/wikipedia/commons/3/30/%E6%B1%9F%E6%B2%B3%E6%B0%B4.ogg",
		duration: 120,
		filesize: 3764321,
		type: "ogg",
		channels: 2,
		bitrate: 128,
		bitdepth: 16,
		samplerate: 44100,
		username: "David290",
		artist: "Zhang Peijian",
		category: "traditional",
		tags: ["chinese", "traditional", "erhu", "instrumental", "oriental", "国风", "古风", "二胡", "民乐", "中国风"],
		license: "CC BY-SA 4.0",
		created: "2024-02-01",
		downloads: 38000,
		rating: 4.9,
		ratingCount: 1520,
	},
	{
		id: 2007,
		name: "爵士钢琴 I Love You (Jazz Piano)",
		description: "Smooth romantic jazz piano rendition for food, cooking and evening vibes",
		url: "https://commons.wikimedia.org/wiki/File:Cole_Porter%E2%80%99s_%E2%80%9CI_Love_You%E2%80%9D_-_JMC,_Han%27s_Piano_Edition.ogg",
		previewUrl: "https://upload.wikimedia.org/wikipedia/commons/4/42/Cole_Porter%E2%80%99s_%E2%80%9CI_Love_You%E2%80%9D_-_JMC%2C_Han%27s_Piano_Edition.ogg",
		downloadUrl: "https://upload.wikimedia.org/wikipedia/commons/4/42/Cole_Porter%E2%80%99s_%E2%80%9CI_Love_You%E2%80%9D_-_JMC%2C_Han%27s_Piano_Edition.ogg",
		duration: 65,
		filesize: 766004,
		type: "ogg",
		channels: 2,
		bitrate: 128,
		bitdepth: 16,
		samplerate: 44100,
		username: "Jason M. C. Han",
		artist: "Jason M. C. Han",
		category: "jazz",
		tags: ["jazz", "piano", "smooth", "romantic", "vintage", "爵士", "钢琴", "浪漫", "复古", "慵懒"],
		license: "CC BY-SA 4.0",
		created: "2024-02-10",
		downloads: 34000,
		rating: 4.8,
		ratingCount: 1250,
	},
];
