export interface TextTemplate {
	id: string;
	name: string;
	category: "hot" | "art" | "variety" | "neon" | "vlog" | "3d" | "bubble" | "title";
	categoryNameZh: string;
	previewText: string;
	isPro?: boolean;
	previewStyle: {
		color: string;
		background?: string;
		textShadow?: string;
		WebkitTextStroke?: string;
		fontFamily?: string;
		fontWeight?: string | number;
		letterSpacing?: string;
		fontStyle?: string;
		boxShadow?: string;
		border?: string;
		borderBottom?: string;
		borderRadius?: string;
		padding?: string;
		textTransform?: "uppercase" | "lowercase" | "capitalize" | "none";
		backgroundImage?: string;
		WebkitBackgroundClip?: string;
		WebkitTextFillColor?: string;
	};
	tags: string[];
	params: {
		content: string;
		fontSize: number;
		fontFamily: string;
		color: string;
		textAlign: "left" | "center" | "right";
		fontWeight: "normal" | "bold";
		fontStyle: "normal" | "italic";
		textDecoration: "none" | "underline" | "line-through";
		letterSpacing: number;
		lineHeight: number;
		"background.enabled": boolean;
		"background.color": string;
		"background.cornerRadius": number;
		"background.paddingX": number;
		"background.paddingY": number;
		"background.offsetX": number;
		"background.offsetY": number;
	};
}

export const CAPCUT_TEXT_CATEGORIES = [
	{ id: "all", label: "🔥 热门" },
	{ id: "variety", label: "🎭 综艺花字" },
	{ id: "art", label: "🎨 艺术字" },
	{ id: "3d", label: "💎 3D立体" },
	{ id: "neon", label: "⚡ 发光霓虹" },
	{ id: "vlog", label: "✨ 潮流Vlog" },
	{ id: "bubble", label: "💭 气泡贴纸" },
	{ id: "title", label: "🎬 电影标题" },
] as const;

export const TEXT_TEMPLATE_CATEGORIES = CAPCUT_TEXT_CATEGORIES;

export const BUILTIN_TEXT_TEMPLATES: TextTemplate[] = [
	// ==========================================
	// 1. 🎭 综艺花字 (Variety & Meme & Trending)
	// ==========================================
	{
		id: "capcut-hot-point",
		name: "划重点",
		category: "variety",
		categoryNameZh: "综艺",
		previewText: "划重点",
		isPro: true,
		previewStyle: {
			color: "#ffffff",
			background: "linear-gradient(180deg, #ff3b30 0%, #ff9500 100%)",
			WebkitTextStroke: "1px #ffffff",
			textShadow: "0 2px 0 #cc0000, 0 4px 6px rgba(0,0,0,0.8)",
			fontWeight: 900,
			padding: "2px 8px",
			borderRadius: "6px",
			boxShadow: "0 3px 0 #b30000, 0 5px 10px rgba(0,0,0,0.5)",
		},
		tags: ["划重点", "重点", "综艺", "红色", "醒目", "爆款", "hot"],
		params: {
			content: "划重点：核心关键要点",
			fontSize: 22,
			fontFamily: "Arial Black",
			color: "#ffffff",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1,
			lineHeight: 1.1,
			"background.enabled": true,
			"background.color": "#ff3b30",
			"background.cornerRadius": 8,
			"background.paddingX": 26,
			"background.paddingY": 34,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-highlight-glow",
		name: "高光时刻",
		category: "variety",
		categoryNameZh: "综艺",
		previewText: "高光时刻",
		isPro: true,
		previewStyle: {
			color: "#fff7d6",
			textShadow: "0 0 10px #ffb700, 0 0 20px #ff6600, 0 0 35px #ff0000",
			fontWeight: 900,
			letterSpacing: "1px",
		},
		tags: ["高光", "高光时刻", "金色", "闪光", "荣耀", "胜利"],
		params: {
			content: "✨ 高光时刻 HIGHLIGHT",
			fontSize: 24,
			fontFamily: "Arial Black",
			color: "#fff7d6",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 2,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#110800",
			"background.cornerRadius": 6,
			"background.paddingX": 30,
			"background.paddingY": 40,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-shock-lines",
		name: "震惊!!",
		category: "variety",
		categoryNameZh: "综艺",
		previewText: "震惊!!",
		isPro: true,
		previewStyle: {
			color: "#38bdf8",
			WebkitTextStroke: "1px #ffffff",
			textShadow: "0 0 10px #0284c7, 2px 2px 0 #0f172a, -2px -2px 0 #0f172a",
			fontWeight: 900,
			letterSpacing: "1px",
		},
		tags: ["震惊", "感叹", "搞笑", "吐槽", "蓝色", "速度线"],
		params: {
			content: "震惊！！居然会这样",
			fontSize: 24,
			fontFamily: "Arial Black",
			color: "#38bdf8",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1.5,
			lineHeight: 1.1,
			"background.enabled": false,
			"background.color": "#000000",
			"background.cornerRadius": 0,
			"background.paddingX": 20,
			"background.paddingY": 30,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-strong-recom",
		name: "强推!",
		category: "variety",
		categoryNameZh: "综艺",
		previewText: "强推!",
		isPro: true,
		previewStyle: {
			color: "#ffffff",
			background: "#ff0044",
			WebkitTextStroke: "1px #ffee00",
			textShadow: "2px 2px 0 #990022",
			fontWeight: 900,
			padding: "2px 8px",
			borderRadius: "4px",
			boxShadow: "0 0 10px #ff0044",
		},
		tags: ["强推", "推荐", "必看", "爆款", "红色", "炸裂"],
		params: {
			content: "强推！闭眼入不踩雷",
			fontSize: 22,
			fontFamily: "Arial Black",
			color: "#ffffff",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1,
			lineHeight: 1.1,
			"background.enabled": true,
			"background.color": "#ff0044",
			"background.cornerRadius": 6,
			"background.paddingX": 26,
			"background.paddingY": 34,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-head-top",
		name: "太上头了",
		category: "variety",
		categoryNameZh: "综艺",
		previewText: "太上头了",
		isPro: true,
		previewStyle: {
			color: "#ffe600",
			WebkitTextStroke: "1px #000000",
			textShadow: "2px 2px 0 #ff0055, 3px 3px 0 #990033",
			fontWeight: 900,
			borderBottom: "2px solid #ffe600",
		},
		tags: ["太上头了", "魔性", "洗脑", "综艺", "黄色", "粉色"],
		params: {
			content: "这也太上头了吧！",
			fontSize: 22,
			fontFamily: "Arial Black",
			color: "#ffe600",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1,
			lineHeight: 1.1,
			"background.enabled": false,
			"background.color": "#000000",
			"background.cornerRadius": 0,
			"background.paddingX": 20,
			"background.paddingY": 30,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-warning-sign",
		name: "⚠️注意",
		category: "variety",
		categoryNameZh: "综艺",
		previewText: "⚠️注意",
		isPro: true,
		previewStyle: {
			color: "#ffffff",
			background: "#e11d48",
			fontWeight: 900,
			padding: "2px 8px",
			borderRadius: "4px",
			boxShadow: "0 0 10px rgba(225,29,72,0.8)",
			letterSpacing: "1px",
		},
		tags: ["注意", "警告", "警示", "危险", "红色", "醒目"],
		params: {
			content: "⚠️ 注意前方高能预警！",
			fontSize: 20,
			fontFamily: "Arial Black",
			color: "#ffffff",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1,
			lineHeight: 1.1,
			"background.enabled": true,
			"background.color": "#e11d48",
			"background.cornerRadius": 6,
			"background.paddingX": 28,
			"background.paddingY": 36,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-depart-now",
		name: "出发喽!",
		category: "variety",
		categoryNameZh: "综艺",
		previewText: "出发喽!",
		isPro: true,
		previewStyle: {
			color: "#38bdf8",
			background: "#ffffff",
			WebkitTextStroke: "1px #0284c7",
			fontWeight: 900,
			padding: "2px 8px",
			borderRadius: "16px",
			boxShadow: "0 3px 0 #0284c7",
		},
		tags: ["出发", "旅行", "Vlog", "蓝色", "可爱", "欢快"],
		params: {
			content: "收拾行李，立即出发喽！",
			fontSize: 20,
			fontFamily: "Arial Black",
			color: "#38bdf8",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#ffffff",
			"background.cornerRadius": 16,
			"background.paddingX": 26,
			"background.paddingY": 34,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-boom-pop",
		name: "爆款夯爆",
		category: "variety",
		categoryNameZh: "综艺",
		previewText: "夯爆了!",
		isPro: true,
		previewStyle: {
			color: "#00ffcc",
			textShadow: "2px 2px 0 #ff0055, -2px -2px 0 #ffcc00",
			fontWeight: 900,
			letterSpacing: "1px",
		},
		tags: ["爆款", "火了", "青色", "潮酷", "潮流"],
		params: {
			content: "这个视频直接夯爆了！",
			fontSize: 22,
			fontFamily: "Arial Black",
			color: "#00ffcc",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1.5,
			lineHeight: 1.1,
			"background.enabled": false,
			"background.color": "#000000",
			"background.cornerRadius": 0,
			"background.paddingX": 20,
			"background.paddingY": 30,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-reliable-gold",
		name: "靠谱!",
		category: "variety",
		categoryNameZh: "综艺",
		previewText: "靠谱",
		isPro: true,
		previewStyle: {
			color: "#ffffff",
			background: "linear-gradient(180deg, #ffb700 0%, #ff5500 100%)",
			WebkitTextStroke: "1px #ffffff",
			textShadow: "1px 1px 0 #880000",
			fontWeight: 900,
			padding: "2px 8px",
			borderRadius: "4px",
		},
		tags: ["靠谱", "赞", "安利", "橙色", "金色"],
		params: {
			content: "这波操作绝对靠谱！",
			fontSize: 22,
			fontFamily: "Arial Black",
			color: "#ffffff",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1,
			lineHeight: 1.1,
			"background.enabled": true,
			"background.color": "#ff8800",
			"background.cornerRadius": 6,
			"background.paddingX": 26,
			"background.paddingY": 34,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-correct-demo",
		name: "正确示范",
		category: "variety",
		categoryNameZh: "综艺",
		previewText: "正确示范",
		isPro: true,
		previewStyle: {
			color: "#ffffff",
			background: "linear-gradient(90deg, #16a34a, #0284c7)",
			fontWeight: "bold",
			padding: "2px 8px",
			borderRadius: "4px",
		},
		tags: ["正确示范", "教学", "对比", "绿色", "蓝色"],
		params: {
			content: "✅ 正确示范：标准规范流程",
			fontSize: 18,
			fontFamily: "Arial",
			color: "#ffffff",
			textAlign: "left",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#16a34a",
			"background.cornerRadius": 4,
			"background.paddingX": 26,
			"background.paddingY": 32,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-variety-crash",
		name: "翻车现场",
		category: "variety",
		categoryNameZh: "综艺",
		previewText: "翻车现场",
		isPro: true,
		previewStyle: {
			color: "#94a3b8",
			background: "#0f172a",
			WebkitTextStroke: "1px #475569",
			textShadow: "0 0 8px rgba(0,0,0,0.9)",
			fontWeight: 900,
			padding: "2px 8px",
			borderRadius: "4px",
			boxShadow: "0 0 12px rgba(15,23,42,0.8)",
		},
		tags: ["翻车", "搞笑", "惨案", "吐槽", "尴尬", "综艺"],
		params: {
			content: "😱 救命！大型翻车现场",
			fontSize: 22,
			fontFamily: "Arial Black",
			color: "#cbd5e1",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1,
			lineHeight: 1.1,
			"background.enabled": true,
			"background.color": "#0f172a",
			"background.cornerRadius": 6,
			"background.paddingX": 28,
			"background.paddingY": 36,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-variety-energy",
		name: "前方高能",
		category: "variety",
		categoryNameZh: "综艺",
		previewText: "⚡前方高能",
		isPro: true,
		previewStyle: {
			color: "#000000",
			background: "#facc15",
			WebkitTextStroke: "1px #000000",
			textShadow: "1px 1px 0 #ffffff",
			fontWeight: 900,
			padding: "2px 8px",
			borderRadius: "4px",
			boxShadow: "0 0 10px rgba(250,204,21,0.7)",
		},
		tags: ["高能", "前方高能", "弹幕", "黄色", "警示", "震撼"],
		params: {
			content: "⚡ 前方高能！非战斗人员速撤",
			fontSize: 22,
			fontFamily: "Arial Black",
			color: "#000000",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1.2,
			lineHeight: 1.1,
			"background.enabled": true,
			"background.color": "#facc15",
			"background.cornerRadius": 6,
			"background.paddingX": 28,
			"background.paddingY": 36,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-variety-crush",
		name: "疯狂心动",
		category: "variety",
		categoryNameZh: "综艺",
		previewText: "💘疯狂心动",
		isPro: true,
		previewStyle: {
			color: "#ffffff",
			background: "linear-gradient(135deg, #ec4899 0%, #f43f5e 100%)",
			WebkitTextStroke: "1px #fff0f5",
			textShadow: "0 2px 4px rgba(236,72,153,0.8)",
			fontWeight: 900,
			padding: "2px 8px",
			borderRadius: "16px",
		},
		tags: ["心动", "恋爱", "粉色", "可爱", "甜宠", "少女心"],
		params: {
			content: "💘 疯狂心动！这也太顶了",
			fontSize: 22,
			fontFamily: "Arial Black",
			color: "#ffffff",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#f43f5e",
			"background.cornerRadius": 16,
			"background.paddingX": 26,
			"background.paddingY": 34,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-variety-zhenxiang",
		name: "真香警告",
		category: "variety",
		categoryNameZh: "综艺",
		previewText: "真香警告",
		isPro: true,
		previewStyle: {
			color: "#ffffff",
			background: "#f97316",
			WebkitTextStroke: "1.2px #7c2d12",
			textShadow: "2px 2px 0 #c2410c",
			fontWeight: 900,
			padding: "2px 8px",
			borderRadius: "6px",
		},
		tags: ["真香", "打脸", "搞笑", "橙色", "综艺", "反转"],
		params: {
			content: "🍗 真香警告！谁能拒绝这个？",
			fontSize: 22,
			fontFamily: "Arial Black",
			color: "#ffffff",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1,
			lineHeight: 1.1,
			"background.enabled": true,
			"background.color": "#f97316",
			"background.cornerRadius": 8,
			"background.paddingX": 26,
			"background.paddingY": 34,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-variety-juejuezi",
		name: "绝绝子",
		category: "variety",
		categoryNameZh: "综艺",
		previewText: "绝绝子!",
		isPro: true,
		previewStyle: {
			color: "#ffffff",
			background: "linear-gradient(135deg, #a855f7 0%, #ec4899 100%)",
			WebkitTextStroke: "1px #ffffff",
			fontWeight: 900,
			padding: "2px 8px",
			borderRadius: "20px",
			boxShadow: "0 4px 10px rgba(168,85,247,0.4)",
		},
		tags: ["绝绝子", "种草", "安利", "美妆", "时尚", "爆款"],
		params: {
			content: "💅 绝绝子！美到窒息的存在",
			fontSize: 22,
			fontFamily: "Arial Black",
			color: "#ffffff",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#a855f7",
			"background.cornerRadius": 18,
			"background.paddingX": 28,
			"background.paddingY": 36,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-variety-nanie",
		name: "狠狠拿捏",
		category: "variety",
		categoryNameZh: "综艺",
		previewText: "狠狠拿捏",
		isPro: true,
		previewStyle: {
			color: "#22c55e",
			WebkitTextStroke: "1px #ffffff",
			textShadow: "2px 2px 0 #14532d, 4px 4px 8px rgba(0,0,0,0.8)",
			fontWeight: 900,
			letterSpacing: "1px",
		},
		tags: ["拿捏", "赢麻了", "霸气", "绿色", "技巧", "教学"],
		params: {
			content: "🎯 狠狠拿捏！这波直接赢麻了",
			fontSize: 22,
			fontFamily: "Arial Black",
			color: "#22c55e",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1.5,
			lineHeight: 1.1,
			"background.enabled": false,
			"background.color": "#000000",
			"background.cornerRadius": 0,
			"background.paddingX": 20,
			"background.paddingY": 30,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-variety-melongossip",
		name: "独家吃瓜",
		category: "variety",
		categoryNameZh: "综艺",
		previewText: "🍉吃瓜速报",
		isPro: true,
		previewStyle: {
			color: "#ffffff",
			background: "#dc2626",
			border: "2px dashed #fef08a",
			fontWeight: 900,
			padding: "2px 8px",
			borderRadius: "4px",
		},
		tags: ["吃瓜", "八卦", "爆料", "速报", "热点"],
		params: {
			content: "🍉 独家吃瓜！一线劲爆速报",
			fontSize: 20,
			fontFamily: "Arial Black",
			color: "#ffffff",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1,
			lineHeight: 1.1,
			"background.enabled": true,
			"background.color": "#dc2626",
			"background.cornerRadius": 4,
			"background.paddingX": 26,
			"background.paddingY": 34,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-variety-soulquestion",
		name: "灵魂发问",
		category: "variety",
		categoryNameZh: "综艺",
		previewText: "灵魂发问?",
		isPro: true,
		previewStyle: {
			color: "#fbbf24",
			WebkitTextStroke: "1px #000000",
			textShadow: "2px 2px 0 #b45309",
			fontWeight: 900,
		},
		tags: ["问号", "疑问", "灵魂拷问", "搞笑", "黄色"],
		params: {
			content: "❓ 灵魂发问：为什么会这样？",
			fontSize: 22,
			fontFamily: "Arial Black",
			color: "#fbbf24",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1,
			lineHeight: 1.1,
			"background.enabled": false,
			"background.color": "#000000",
			"background.cornerRadius": 0,
			"background.paddingX": 20,
			"background.paddingY": 30,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-variety-blackboard",
		name: "敲黑板",
		category: "variety",
		categoryNameZh: "综艺",
		previewText: "📌敲黑板",
		isPro: true,
		previewStyle: {
			color: "#fef08a",
			background: "#14532d",
			border: "1.5px solid #22c55e",
			fontWeight: 900,
			padding: "2px 8px",
			borderRadius: "4px",
		},
		tags: ["敲黑板", "划重点", "干货", "知识", "教学", "绿色"],
		params: {
			content: "📌 敲黑板！本期核心干货总结",
			fontSize: 20,
			fontFamily: "Arial",
			color: "#fef08a",
			textAlign: "left",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#14532d",
			"background.cornerRadius": 6,
			"background.paddingX": 28,
			"background.paddingY": 36,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-variety-lol",
		name: "笑不活了",
		category: "variety",
		categoryNameZh: "综艺",
		previewText: "🤣笑不活了",
		isPro: true,
		previewStyle: {
			color: "#facc15",
			WebkitTextStroke: "1px #000000",
			textShadow: "2px 2px 0 #ef4444, 4px 4px 0 #000000",
			fontWeight: 900,
		},
		tags: ["搞笑", "笑不活了", "哈哈", "爆笑", "综艺"],
		params: {
			content: "🤣 哈哈哈哈！直接笑到头掉",
			fontSize: 22,
			fontFamily: "Arial Black",
			color: "#facc15",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1.5,
			lineHeight: 1.1,
			"background.enabled": false,
			"background.color": "#000000",
			"background.cornerRadius": 0,
			"background.paddingX": 20,
			"background.paddingY": 30,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-variety-pofang",
		name: "破防瞬间",
		category: "variety",
		categoryNameZh: "综艺",
		previewText: "😭破防了",
		isPro: true,
		previewStyle: {
			color: "#38bdf8",
			background: "#1e293b",
			WebkitTextStroke: "1px #0284c7",
			fontWeight: 900,
			padding: "2px 8px",
			borderRadius: "4px",
		},
		tags: ["破防", "扎心", "emo", "感动", "泪目"],
		params: {
			content: "😭 这一刻我真的彻底破防了",
			fontSize: 20,
			fontFamily: "Arial Black",
			color: "#38bdf8",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#1e293b",
			"background.cornerRadius": 6,
			"background.paddingX": 26,
			"background.paddingY": 34,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},

	// ==========================================
	// 2. 🎨 艺术字 (Art & Stylized Text)
	// ==========================================
	{
		id: "capcut-art-gold-bevel",
		name: "立体金光花字",
		category: "art",
		categoryNameZh: "艺术字",
		previewText: "花字",
		isPro: true,
		previewStyle: {
			color: "#ffdf00",
			WebkitTextStroke: "1px #704200",
			textShadow: "1px 1px 0 #502e00, 2px 2px 0 #301b00, 3px 3px 6px rgba(0,0,0,0.9)",
			fontWeight: 900,
		},
		tags: ["花字", "金色", "立体", "质感", "金光"],
		params: {
			content: "精彩花字标题",
			fontSize: 24,
			fontFamily: "Arial Black",
			color: "#ffdf00",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 2,
			lineHeight: 1.1,
			"background.enabled": false,
			"background.color": "#000000",
			"background.cornerRadius": 0,
			"background.paddingX": 20,
			"background.paddingY": 30,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-art-dark-metal",
		name: "黑曜金属花字",
		category: "art",
		categoryNameZh: "艺术字",
		previewText: "花字",
		isPro: true,
		previewStyle: {
			color: "#222226",
			WebkitTextStroke: "1.5px #71717a",
			textShadow: "2px 2px 0 #09090b, 0 0 10px rgba(0,0,0,0.8)",
			fontWeight: 900,
		},
		tags: ["金属", "黑色", "硬核", "科技", "深色"],
		params: {
			content: "黑曜金属质感",
			fontSize: 24,
			fontFamily: "Arial Black",
			color: "#222226",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 2,
			lineHeight: 1.1,
			"background.enabled": false,
			"background.color": "#000000",
			"background.cornerRadius": 0,
			"background.paddingX": 20,
			"background.paddingY": 30,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-art-fire-flame",
		name: "烈焰烈火花字",
		category: "art",
		categoryNameZh: "艺术字",
		previewText: "花字",
		isPro: true,
		previewStyle: {
			color: "#ffffff",
			WebkitTextStroke: "1.5px #ffea00",
			textShadow: "0 0 10px #ff0000, 0 0 20px #ff5500, 2px 2px 0 #990000",
			fontWeight: 900,
		},
		tags: ["火焰", "烈焰", "燃烧", "红色", "黄色", "高燃"],
		params: {
			content: "高燃热血来袭",
			fontSize: 24,
			fontFamily: "Arial Black",
			color: "#ffffff",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1.5,
			lineHeight: 1.1,
			"background.enabled": false,
			"background.color": "#000000",
			"background.cornerRadius": 0,
			"background.paddingX": 20,
			"background.paddingY": 30,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-art-red-white-stroke",
		name: "红白双层描边",
		category: "art",
		categoryNameZh: "艺术字",
		previewText: "花字",
		isPro: true,
		previewStyle: {
			color: "#ff1744",
			WebkitTextStroke: "1.5px #ffffff",
			textShadow: "3px 3px 0 #000000, -1px -1px 0 #ffffff",
			fontWeight: 900,
		},
		tags: ["红白", "双层", "描边", "可爱", "经典"],
		params: {
			content: "红白双层描边花字",
			fontSize: 24,
			fontFamily: "Arial Black",
			color: "#ff1744",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1.5,
			lineHeight: 1.1,
			"background.enabled": false,
			"background.color": "#000000",
			"background.cornerRadius": 0,
			"background.paddingX": 20,
			"background.paddingY": 30,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-art-yellow-box",
		name: "黄底撕纸花字",
		category: "art",
		categoryNameZh: "艺术字",
		previewText: "花字",
		isPro: true,
		previewStyle: {
			color: "#ffffff",
			background: "#ffcc00",
			WebkitTextStroke: "1px #000000",
			fontWeight: 900,
			padding: "2px 8px",
			borderRadius: "2px",
			boxShadow: "2px 2px 0 #000000",
		},
		tags: ["黄底", "黑边", "醒目", "撕纸", "贴纸"],
		params: {
			content: "醒目黄底黑边标题",
			fontSize: 22,
			fontFamily: "Arial Black",
			color: "#ffffff",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1,
			lineHeight: 1.1,
			"background.enabled": true,
			"background.color": "#ffcc00",
			"background.cornerRadius": 4,
			"background.paddingX": 26,
			"background.paddingY": 34,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-art-blue-bubble",
		name: "炫蓝气泡花字",
		category: "art",
		categoryNameZh: "艺术字",
		previewText: "花字",
		isPro: true,
		previewStyle: {
			color: "#ffffff",
			background: "#0284c7",
			WebkitTextStroke: "1px #bae6fd",
			fontWeight: 900,
			padding: "2px 8px",
			borderRadius: "8px",
			boxShadow: "0 0 10px #0284c7",
		},
		tags: ["炫蓝", "气泡", "科技", "蓝色", "清新"],
		params: {
			content: "炫蓝气泡立体花字",
			fontSize: 22,
			fontFamily: "Arial Black",
			color: "#ffffff",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1,
			lineHeight: 1.1,
			"background.enabled": true,
			"background.color": "#0284c7",
			"background.cornerRadius": 8,
			"background.paddingX": 26,
			"background.paddingY": 34,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-art-black-white-pop",
		name: "经典黑白描边",
		category: "art",
		categoryNameZh: "艺术字",
		previewText: "花字",
		isPro: true,
		previewStyle: {
			color: "#ffffff",
			WebkitTextStroke: "2px #000000",
			textShadow: "3px 3px 0 #000000",
			fontWeight: 900,
		},
		tags: ["黑白", "描边", "解说", "醒目", "波普"],
		params: {
			content: "经典黑白描边大字",
			fontSize: 24,
			fontFamily: "Arial Black",
			color: "#ffffff",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1.5,
			lineHeight: 1.1,
			"background.enabled": false,
			"background.color": "#000000",
			"background.cornerRadius": 0,
			"background.paddingX": 20,
			"background.paddingY": 30,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-art-glitch-split",
		name: "赛博故障Glitch",
		category: "art",
		categoryNameZh: "艺术字",
		previewText: "GLITCH",
		isPro: true,
		previewStyle: {
			color: "#ffffff",
			textShadow: "-2px 0 #ff0055, 2px 0 #00ffff, 0 0 8px rgba(255,255,255,0.6)",
			fontWeight: 900,
			letterSpacing: "3px",
		},
		tags: ["故障", "赛博", "Glitch", "RGB", "潮流", "朋克"],
		params: {
			content: "SYSTEM GLITCH // 2077",
			fontSize: 24,
			fontFamily: "Arial Black",
			color: "#ffffff",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 3,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#09090b",
			"background.cornerRadius": 4,
			"background.paddingX": 30,
			"background.paddingY": 40,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-art-retro-pop",
		name: "80s复古波普",
		category: "art",
		categoryNameZh: "艺术字",
		previewText: "POPART!",
		isPro: true,
		previewStyle: {
			color: "#fde047",
			WebkitTextStroke: "1.5px #000000",
			textShadow: "3px 3px 0 #ec4899, 6px 6px 0 #06b6d4",
			fontWeight: 900,
		},
		tags: ["波普", "复古", "80s", "潮流", "彩色", "黄色"],
		params: {
			content: "RETRO POP ART VIBE",
			fontSize: 24,
			fontFamily: "Arial Black",
			color: "#fde047",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 2,
			lineHeight: 1.1,
			"background.enabled": false,
			"background.color": "#000000",
			"background.cornerRadius": 0,
			"background.paddingX": 20,
			"background.paddingY": 30,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-art-rainbow-candy",
		name: "炫彩梦幻糖果",
		category: "art",
		categoryNameZh: "艺术字",
		previewText: "CANDY",
		isPro: true,
		previewStyle: {
			color: "#ffffff",
			background: "linear-gradient(90deg, #f43f5e, #eab308, #06b6d4, #a855f7)",
			WebkitTextStroke: "1px #ffffff",
			fontWeight: 900,
			padding: "2px 8px",
			borderRadius: "16px",
			boxShadow: "0 4px 12px rgba(244,63,94,0.4)",
		},
		tags: ["彩虹", "糖果", "甜美", "彩色", "可爱", "梦幻"],
		params: {
			content: "🌈 SWEET CANDY DREAM",
			fontSize: 22,
			fontFamily: "Arial Black",
			color: "#ffffff",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1.5,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#ec4899",
			"background.cornerRadius": 16,
			"background.paddingX": 28,
			"background.paddingY": 36,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-art-chinese-ink",
		name: "东方水墨朱砂",
		category: "art",
		categoryNameZh: "艺术字",
		previewText: "山水",
		isPro: true,
		previewStyle: {
			color: "#f8fafc",
			background: "#18181b",
			border: "1px solid #dc2626",
			textShadow: "0 0 8px rgba(220,38,38,0.6)",
			fontWeight: "bold",
			fontFamily: "Georgia, serif",
			padding: "2px 8px",
			borderRadius: "2px",
		},
		tags: ["水墨", "国风", "东方", "古风", "朱砂", "书法"],
		params: {
			content: "山水画境 · 东方美学",
			fontSize: 22,
			fontFamily: "Georgia",
			color: "#f8fafc",
			textAlign: "center",
			fontWeight: "normal",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 4,
			lineHeight: 1.3,
			"background.enabled": true,
			"background.color": "#18181b",
			"background.cornerRadius": 2,
			"background.paddingX": 32,
			"background.paddingY": 42,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-art-sunset-glow",
		name: "暮色落日余晖",
		category: "art",
		categoryNameZh: "艺术字",
		previewText: "SUNSET",
		isPro: true,
		previewStyle: {
			color: "#fde047",
			background: "linear-gradient(180deg, #7c3aed 0%, #db2777 50%, #f59e0b 100%)",
			WebkitTextStroke: "1px #ffffff",
			fontWeight: 900,
			padding: "2px 8px",
			borderRadius: "8px",
		},
		tags: ["日落", "余晖", "晚霞", "紫橙", "唯美", "治愈"],
		params: {
			content: "SUNSET HORIZON 追光之旅",
			fontSize: 22,
			fontFamily: "Arial Black",
			color: "#fde047",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 2,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#7c3aed",
			"background.cornerRadius": 8,
			"background.paddingX": 28,
			"background.paddingY": 36,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-art-matcha-cheese",
		name: "抹茶芝士森系",
		category: "art",
		categoryNameZh: "艺术字",
		previewText: "MATCHA",
		isPro: true,
		previewStyle: {
			color: "#15803d",
			background: "#fef9c3",
			border: "1.5px solid #86efac",
			fontWeight: 900,
			padding: "2px 8px",
			borderRadius: "12px",
		},
		tags: ["抹茶", "森系", "清新", "自然", "绿色", "淡雅"],
		params: {
			content: "MATCHA & GREEN 森林系清晨",
			fontSize: 20,
			fontFamily: "Arial Black",
			color: "#15803d",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#fef9c3",
			"background.cornerRadius": 12,
			"background.paddingX": 26,
			"background.paddingY": 34,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},

	// ==========================================
	// 3. 💎 3D 立体与金属质感 (3D & Metallic)
	// ==========================================
	{
		id: "capcut-3d-silver",
		name: "3D电镀白银",
		category: "3d",
		categoryNameZh: "3D",
		previewText: "SILVER",
		isPro: true,
		previewStyle: {
			color: "#f8fafc",
			textShadow: "0 1px 0 #cbd5e1, 0 2px 0 #94a3b8, 0 3px 0 #64748b, 0 4px 0 #475569, 0 6px 10px rgba(0,0,0,0.9)",
			fontWeight: 900,
			letterSpacing: "2px",
		},
		tags: ["3D", "银色", "金属", "电镀", "未来", "质感"],
		params: {
			content: "CHROME METALLIC 3D",
			fontSize: 24,
			fontFamily: "Arial Black",
			color: "#f8fafc",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 2,
			lineHeight: 1.2,
			"background.enabled": false,
			"background.color": "#000000",
			"background.cornerRadius": 0,
			"background.paddingX": 20,
			"background.paddingY": 30,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-3d-ruby",
		name: "3D红宝石",
		category: "3d",
		categoryNameZh: "3D",
		previewText: "RUBY",
		isPro: true,
		previewStyle: {
			color: "#ff2a5f",
			textShadow: "0 1px 0 #cc1144, 0 2px 0 #990033, 0 3px 0 #660022, 0 5px 8px rgba(0,0,0,0.9)",
			fontWeight: 900,
			letterSpacing: "2px",
		},
		tags: ["3D", "红宝石", "奢华", "红色", "立体"],
		params: {
			content: "RUBY EDITION 奢华红宝",
			fontSize: 24,
			fontFamily: "Arial Black",
			color: "#ff2a5f",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 2,
			lineHeight: 1.2,
			"background.enabled": false,
			"background.color": "#000000",
			"background.cornerRadius": 0,
			"background.paddingX": 20,
			"background.paddingY": 30,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-3d-pure-gold",
		name: "3D至尊土豪金",
		category: "3d",
		categoryNameZh: "3D",
		previewText: "GOLD",
		isPro: true,
		previewStyle: {
			color: "#ffd700",
			textShadow: "0 1px 0 #d4af37, 0 2px 0 #aa8c2c, 0 3px 0 #806921, 0 4px 0 #554616, 0 6px 12px rgba(0,0,0,0.9)",
			fontWeight: 900,
			letterSpacing: "2px",
		},
		tags: ["3D", "纯金", "土豪金", "奢华", "金色", "尊贵"],
		params: {
			content: "PREMIUM GOLD 3D EDITION",
			fontSize: 24,
			fontFamily: "Arial Black",
			color: "#ffd700",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 2.5,
			lineHeight: 1.2,
			"background.enabled": false,
			"background.color": "#000000",
			"background.cornerRadius": 0,
			"background.paddingX": 20,
			"background.paddingY": 30,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-3d-bubble-balloon",
		name: "3D梦幻充气气球",
		category: "3d",
		categoryNameZh: "3D",
		previewText: "BALLOON",
		isPro: true,
		previewStyle: {
			color: "#f472b6",
			textShadow: "0 2px 0 #db2777, 0 4px 0 #9d174d, 0 6px 10px rgba(219,39,119,0.5)",
			fontWeight: 900,
			letterSpacing: "2px",
		},
		tags: ["3D", "气球", "充气", "粉色", "可爱", "立体"],
		params: {
			content: "POP BALLOON 梦幻充气感",
			fontSize: 24,
			fontFamily: "Arial Black",
			color: "#f472b6",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 2,
			lineHeight: 1.2,
			"background.enabled": false,
			"background.color": "#000000",
			"background.cornerRadius": 0,
			"background.paddingX": 20,
			"background.paddingY": 30,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-3d-ice-crystal",
		name: "3D极地冰霜水晶",
		category: "3d",
		categoryNameZh: "3D",
		previewText: "FROZEN",
		isPro: true,
		previewStyle: {
			color: "#bae6fd",
			textShadow: "0 1px 0 #7dd3fc, 0 2px 0 #38bdf8, 0 3px 0 #0284c7, 0 5px 12px rgba(2,132,199,0.8)",
			fontWeight: 900,
			letterSpacing: "2px",
		},
		tags: ["3D", "冰霜", "水晶", "蓝色", "极寒", "清凉"],
		params: {
			content: "FROZEN ICE 极地冰晶",
			fontSize: 24,
			fontFamily: "Arial Black",
			color: "#bae6fd",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 2,
			lineHeight: 1.2,
			"background.enabled": false,
			"background.color": "#000000",
			"background.cornerRadius": 0,
			"background.paddingX": 20,
			"background.paddingY": 30,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-3d-lava-magma",
		name: "3D熔岩炽热核心",
		category: "3d",
		categoryNameZh: "3D",
		previewText: "LAVA 3D",
		isPro: true,
		previewStyle: {
			color: "#fb923c",
			textShadow: "0 1px 0 #ea580c, 0 2px 0 #9a3412, 0 3px 0 #431407, 0 0 16px #ff4500",
			fontWeight: 900,
			letterSpacing: "2px",
		},
		tags: ["3D", "熔岩", "火焰", "炽热", "橙红", "震撼"],
		params: {
			content: "VOLCANIC LAVA 炽热熔岩",
			fontSize: 24,
			fontFamily: "Arial Black",
			color: "#fb923c",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 2,
			lineHeight: 1.2,
			"background.enabled": false,
			"background.color": "#000000",
			"background.cornerRadius": 0,
			"background.paddingX": 20,
			"background.paddingY": 30,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-3d-cyber-amethyst",
		name: "3D赛博紫晶矿石",
		category: "3d",
		categoryNameZh: "3D",
		previewText: "CRYSTAL",
		isPro: true,
		previewStyle: {
			color: "#c084fc",
			textShadow: "0 1px 0 #9333ea, 0 2px 0 #6b21a8, 0 3px 0 #3b0764, 0 0 14px #a855f7",
			fontWeight: 900,
			letterSpacing: "2px",
		},
		tags: ["3D", "紫晶", "水晶", "紫色", "矿石", "未来"],
		params: {
			content: "CYBER AMETHYST 3D",
			fontSize: 24,
			fontFamily: "Arial Black",
			color: "#c084fc",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 2,
			lineHeight: 1.2,
			"background.enabled": false,
			"background.color": "#000000",
			"background.cornerRadius": 0,
			"background.paddingX": 20,
			"background.paddingY": 30,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},

	// ==========================================
	// 4. ⚡ 发光霓虹 (Neon & Glow)
	// ==========================================
	{
		id: "capcut-neon-cyan",
		name: "赛博霓虹青",
		category: "neon",
		categoryNameZh: "发光",
		previewText: "NEON",
		isPro: true,
		previewStyle: {
			color: "#00f0ff",
			textShadow: "0 0 6px #00f0ff, 0 0 15px #00aaff, 0 0 28px #0066ff",
			fontWeight: 900,
			letterSpacing: "3px",
		},
		tags: ["霓虹", "青色", "赛博", "科幻", "发光"],
		params: {
			content: "CYBER NEON 2077",
			fontSize: 24,
			fontFamily: "Arial",
			color: "#00f0ff",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 3,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#020a16",
			"background.cornerRadius": 6,
			"background.paddingX": 32,
			"background.paddingY": 42,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-neon-purple",
		name: "极光激光紫",
		category: "neon",
		categoryNameZh: "发光",
		previewText: "LASER",
		isPro: true,
		previewStyle: {
			color: "#f050ff",
			textShadow: "0 0 6px #f050ff, 0 0 18px #aa00ff, 0 0 32px #6200ea",
			fontWeight: 900,
			letterSpacing: "3px",
		},
		tags: ["激光", "紫色", "极光", "电音", "舞台"],
		params: {
			content: "LASER NIGHT DANCE",
			fontSize: 22,
			fontFamily: "Arial",
			color: "#f050ff",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 2,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#0c0217",
			"background.cornerRadius": 6,
			"background.paddingX": 30,
			"background.paddingY": 40,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-neon-green",
		name: "矩阵代码绿",
		category: "neon",
		categoryNameZh: "发光",
		previewText: "MATRIX",
		isPro: true,
		previewStyle: {
			color: "#00ff66",
			textShadow: "0 0 6px #00ff66, 0 0 16px #00cc33, 0 0 28px #005511",
			fontFamily: "monospace",
			fontWeight: 900,
			letterSpacing: "2px",
		},
		tags: ["矩阵", "黑客", "代码", "绿色", "终端"],
		params: {
			content: "SYSTEM OVERRIDE // 01",
			fontSize: 18,
			fontFamily: "Courier New",
			color: "#00ff66",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 2,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#001105",
			"background.cornerRadius": 4,
			"background.paddingX": 28,
			"background.paddingY": 38,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-art-white-glow",
		name: "纯白光晕花字",
		category: "neon",
		categoryNameZh: "发光",
		previewText: "GLOW",
		isPro: true,
		previewStyle: {
			color: "#ffffff",
			textShadow: "0 0 8px #ffffff, 0 0 18px rgba(255,255,255,0.8), 0 0 30px rgba(255,255,255,0.5)",
			fontWeight: 900,
		},
		tags: ["白色", "发光", "光晕", "唯美", "纯洁"],
		params: {
			content: "纯白唯美光晕",
			fontSize: 24,
			fontFamily: "Arial",
			color: "#ffffff",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 2,
			lineHeight: 1.2,
			"background.enabled": false,
			"background.color": "#000000",
			"background.cornerRadius": 0,
			"background.paddingX": 20,
			"background.paddingY": 30,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-neon-miami-sunset",
		name: "迈阿密粉红落日",
		category: "neon",
		categoryNameZh: "发光",
		previewText: "SYNTH",
		isPro: true,
		previewStyle: {
			color: "#ff2a85",
			textShadow: "0 0 8px #ff2a85, 0 0 20px #ff007f, 0 0 32px #aa0055",
			fontWeight: 900,
			letterSpacing: "2px",
		},
		tags: ["迈阿密", "粉红", "复古", "合成波", "发光", "80s"],
		params: {
			content: "MIAMI RETRO WAVE 80S",
			fontSize: 22,
			fontFamily: "Arial Black",
			color: "#ff2a85",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 2,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#160012",
			"background.cornerRadius": 6,
			"background.paddingX": 30,
			"background.paddingY": 40,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-neon-crimson-red",
		name: "炽热绯红霓虹",
		category: "neon",
		categoryNameZh: "发光",
		previewText: "CRIMSON",
		isPro: true,
		previewStyle: {
			color: "#ff1e42",
			textShadow: "0 0 8px #ff1e42, 0 0 20px #ff002b, 0 0 35px #990014",
			fontWeight: 900,
			letterSpacing: "2px",
		},
		tags: ["红色", "绯红", "酒吧", "招牌", "热烈", "霓虹"],
		params: {
			content: "CRIMSON NIGHT BAR",
			fontSize: 22,
			fontFamily: "Arial",
			color: "#ff1e42",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 2,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#180005",
			"background.cornerRadius": 6,
			"background.paddingX": 30,
			"background.paddingY": 40,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-neon-electric-yellow",
		name: "荧光高亮电光黄",
		category: "neon",
		categoryNameZh: "发光",
		previewText: "VOLT",
		isPro: true,
		previewStyle: {
			color: "#fef08a",
			textShadow: "0 0 8px #eab308, 0 0 20px #ca8a04, 0 0 32px #854d0e",
			fontWeight: 900,
			letterSpacing: "2px",
		},
		tags: ["黄色", "荧光", "电压", "发光", "醒目"],
		params: {
			content: "HIGH VOLTAGE 220V",
			fontSize: 22,
			fontFamily: "Arial Black",
			color: "#fef08a",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 2,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#140f00",
			"background.cornerRadius": 6,
			"background.paddingX": 30,
			"background.paddingY": 40,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-neon-warm-amber",
		name: "琥珀暖金光晕",
		category: "neon",
		categoryNameZh: "发光",
		previewText: "AMBER",
		isPro: true,
		previewStyle: {
			color: "#fed7aa",
			textShadow: "0 0 8px #f97316, 0 0 20px #ea580c, 0 0 30px #9a3412",
			fontWeight: 900,
			letterSpacing: "2px",
		},
		tags: ["琥珀", "暖光", "温暖", "治愈", "金光"],
		params: {
			content: "WARM AMBER GLOW 温暖时刻",
			fontSize: 22,
			fontFamily: "Georgia",
			color: "#fed7aa",
			textAlign: "center",
			fontWeight: "normal",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 2,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#180900",
			"background.cornerRadius": 6,
			"background.paddingX": 30,
			"background.paddingY": 40,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},

	// ==========================================
	// 5. ✨ 潮流Vlog (Vlog & Lifestyle)
	// ==========================================
	{
		id: "capcut-signature-chic",
		name: "手写签名",
		category: "vlog",
		categoryNameZh: "Vlog",
		previewText: "Signature",
		isPro: true,
		previewStyle: {
			color: "#f8fafc",
			fontFamily: "Georgia, 'Brush Script MT', cursive",
			fontStyle: "italic",
			letterSpacing: "1.5px",
		},
		tags: ["手写", "英文", "高级", "签名", "胶片", "法式"],
		params: {
			content: "Signature Collection · Vol.01",
			fontSize: 20,
			fontFamily: "Georgia",
			color: "#f8fafc",
			textAlign: "center",
			fontWeight: "normal",
			fontStyle: "italic",
			textDecoration: "none",
			letterSpacing: 2,
			lineHeight: 1.2,
			"background.enabled": false,
			"background.color": "#000000",
			"background.cornerRadius": 0,
			"background.paddingX": 20,
			"background.paddingY": 30,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-daily-record",
		name: "#记录日常",
		category: "vlog",
		categoryNameZh: "Vlog",
		previewText: "#记录日常",
		isPro: true,
		previewStyle: {
			color: "#ffffff",
			background: "#1e293b",
			border: "1px solid #475569",
			padding: "2px 8px",
			borderRadius: "4px",
			fontWeight: "bold",
		},
		tags: ["记录日常", "vlog", "日常", "极简", "标签"],
		params: {
			content: "#记录美好日常生活",
			fontSize: 16,
			fontFamily: "Arial",
			color: "#ffffff",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#1e293b",
			"background.cornerRadius": 6,
			"background.paddingX": 24,
			"background.paddingY": 32,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-vlog-japanese-film",
		name: "日系清新胶片",
		category: "vlog",
		categoryNameZh: "Vlog",
		previewText: "日日是好日",
		isPro: true,
		previewStyle: {
			color: "#334155",
			background: "#f8fafc",
			border: "1px solid #cbd5e1",
			fontFamily: "Georgia, serif",
			padding: "2px 8px",
			borderRadius: "2px",
			letterSpacing: "1px",
		},
		tags: ["日系", "胶片", "清新", "治愈", "生活", "胶卷"],
		params: {
			content: "日日是好日 · 晴朗日常记事",
			fontSize: 18,
			fontFamily: "Georgia",
			color: "#334155",
			textAlign: "center",
			fontWeight: "normal",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 2,
			lineHeight: 1.3,
			"background.enabled": true,
			"background.color": "#f8fafc",
			"background.cornerRadius": 2,
			"background.paddingX": 26,
			"background.paddingY": 34,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-vlog-french-serif",
		name: "法式复古衬线",
		category: "vlog",
		categoryNameZh: "Vlog",
		previewText: "L'AMOUR",
		isPro: true,
		previewStyle: {
			color: "#fafaf9",
			fontFamily: "Georgia, serif",
			letterSpacing: "4px",
			textShadow: "0 2px 8px rgba(0,0,0,0.8)",
			fontWeight: 300,
		},
		tags: ["法式", "复古", "衬线", "浪漫", "优雅", "高级"],
		params: {
			content: "L'AMOUR TOUJOURS · PARIS",
			fontSize: 20,
			fontFamily: "Georgia",
			color: "#fafaf9",
			textAlign: "center",
			fontWeight: "normal",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 4,
			lineHeight: 1.3,
			"background.enabled": false,
			"background.color": "#000000",
			"background.cornerRadius": 0,
			"background.paddingX": 20,
			"background.paddingY": 30,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-vlog-citywalk-tag",
		name: "城市漫步Citywalk",
		category: "vlog",
		categoryNameZh: "Vlog",
		previewText: "📍Citywalk",
		isPro: true,
		previewStyle: {
			color: "#ffffff",
			background: "#0f766e",
			padding: "2px 8px",
			borderRadius: "16px",
			fontWeight: "bold",
		},
		tags: ["Citywalk", "城市漫步", "打卡", "旅行", "探店", "标签"],
		params: {
			content: "📍 CITYWALK · 城市街巷漫游指南",
			fontSize: 18,
			fontFamily: "Arial",
			color: "#ffffff",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#0f766e",
			"background.cornerRadius": 16,
			"background.paddingX": 28,
			"background.paddingY": 36,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-vlog-coffee-latte",
		name: "咖啡时光Cafe",
		category: "vlog",
		categoryNameZh: "Vlog",
		previewText: "☕ Coffee",
		isPro: true,
		previewStyle: {
			color: "#451a03",
			background: "#fef3c7",
			border: "1px solid #d97706",
			padding: "2px 8px",
			borderRadius: "6px",
			fontWeight: "bold",
		},
		tags: ["咖啡", "下午茶", "拿铁", "暖色", "慢生活", "治愈"],
		params: {
			content: "☕ COFFEE & MORNING 早安咖啡时光",
			fontSize: 18,
			fontFamily: "Georgia",
			color: "#451a03",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#fef3c7",
			"background.cornerRadius": 6,
			"background.paddingX": 26,
			"background.paddingY": 34,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-vlog-ootd-magazine",
		name: "每日穿搭OOTD",
		category: "vlog",
		categoryNameZh: "Vlog",
		previewText: "OOTD LOOK",
		isPro: true,
		previewStyle: {
			color: "#18181b",
			background: "#ffffff",
			border: "2px solid #18181b",
			padding: "2px 8px",
			fontWeight: 900,
			letterSpacing: "1px",
		},
		tags: ["OOTD", "穿搭", "时尚", "杂志", "排版", "潮流"],
		params: {
			content: "OOTD · TODAY'S AUTUMN LOOK",
			fontSize: 18,
			fontFamily: "Arial Black",
			color: "#18181b",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 2,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#ffffff",
			"background.cornerRadius": 0,
			"background.paddingX": 28,
			"background.paddingY": 36,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-vlog-unboxing-dark",
		name: "沉浸式开箱",
		category: "vlog",
		categoryNameZh: "Vlog",
		previewText: "📦UNBOXING",
		isPro: true,
		previewStyle: {
			color: "#f8fafc",
			background: "rgba(15, 23, 42, 0.85)",
			border: "1px solid rgba(255,255,255,0.15)",
			padding: "2px 8px",
			borderRadius: "8px",
			fontWeight: "bold",
			letterSpacing: "1px",
		},
		tags: ["开箱", "沉浸式", "好物", "数码", "测评"],
		params: {
			content: "📦 UNBOXING · 沉浸式开箱新装备",
			fontSize: 18,
			fontFamily: "Arial",
			color: "#f8fafc",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1.5,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "rgba(15, 23, 42, 0.85)",
			"background.cornerRadius": 8,
			"background.paddingX": 28,
			"background.paddingY": 36,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-vlog-music-lyric",
		name: "氛围感歌词",
		category: "vlog",
		categoryNameZh: "Vlog",
		previewText: "🎵 歌词字幕",
		isPro: true,
		previewStyle: {
			color: "#f1f5f9",
			background: "rgba(0, 0, 0, 0.65)",
			padding: "2px 8px",
			borderRadius: "16px",
			fontStyle: "italic",
		},
		tags: ["歌词", "音乐", "氛围感", "浪漫", "深夜", "字幕"],
		params: {
			content: "🎵 这一瞬间，时间好像静止了...",
			fontSize: 16,
			fontFamily: "Georgia",
			color: "#f1f5f9",
			textAlign: "center",
			fontWeight: "normal",
			fontStyle: "italic",
			textDecoration: "none",
			letterSpacing: 1,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "rgba(0, 0, 0, 0.7)",
			"background.cornerRadius": 16,
			"background.paddingX": 26,
			"background.paddingY": 34,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-vlog-rec-badge",
		name: "REC录像水印",
		category: "vlog",
		categoryNameZh: "Vlog",
		previewText: "● REC 00:00",
		isPro: true,
		previewStyle: {
			color: "#ffffff",
			fontFamily: "monospace",
			fontWeight: "bold",
			textShadow: "0 0 4px #ff0000",
		},
		tags: ["REC", "录像", "相机", "时间码", "胶片", "水印"],
		params: {
			content: "● REC 00:01:24:18 [4K 60FPS]",
			fontSize: 15,
			fontFamily: "Courier New",
			color: "#ffffff",
			textAlign: "left",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1.5,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "rgba(0,0,0,0.5)",
			"background.cornerRadius": 4,
			"background.paddingX": 22,
			"background.paddingY": 28,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},

	// ==========================================
	// 6. 💭 气泡与对话贴纸 (Bubbles & Stickers)
	// ==========================================
	{
		id: "capcut-bubble-comic-white",
		name: "漫画对话气泡",
		category: "bubble",
		categoryNameZh: "气泡",
		previewText: "OMG?!",
		isPro: true,
		previewStyle: {
			color: "#111111",
			background: "#ffffff",
			border: "2px solid #111111",
			borderRadius: "16px",
			fontWeight: 900,
			padding: "2px 10px",
		},
		tags: ["气泡", "漫画", "对话", "惊讶"],
		params: {
			content: "等等，居然是这样？！",
			fontSize: 16,
			fontFamily: "Arial Black",
			color: "#111111",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 0.5,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#ffffff",
			"background.cornerRadius": 16,
			"background.paddingX": 26,
			"background.paddingY": 34,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-bubble-pixel-8bit",
		name: "8Bit像素任务",
		category: "bubble",
		categoryNameZh: "气泡",
		previewText: "> Quest!",
		isPro: true,
		previewStyle: {
			color: "#ffffff",
			background: "#1e1b4b",
			border: "2px solid #818cf8",
			fontFamily: "monospace",
			fontWeight: "bold",
			padding: "2px 8px",
		},
		tags: ["像素", "游戏", "8bit", "任务"],
		params: {
			content: "> 新任务已解锁，准备出发！",
			fontSize: 14,
			fontFamily: "Courier New",
			color: "#ffffff",
			textAlign: "left",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#1e1b4b",
			"background.cornerRadius": 0,
			"background.paddingX": 24,
			"background.paddingY": 30,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-bubble-cute-pink",
		name: "萌宠爪爪粉泡",
		category: "bubble",
		categoryNameZh: "气泡",
		previewText: "🐾喵~",
		isPro: true,
		previewStyle: {
			color: "#db2777",
			background: "#fce7f3",
			border: "2px solid #f472b6",
			borderRadius: "18px",
			fontWeight: 900,
			padding: "2px 8px",
		},
		tags: ["可爱", "萌宠", "粉色", "猫咪", "爪爪", "气泡"],
		params: {
			content: "🐾 喵~ 谁在叫本可爱呀？",
			fontSize: 16,
			fontFamily: "Arial Black",
			color: "#db2777",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#fce7f3",
			"background.cornerRadius": 18,
			"background.paddingX": 26,
			"background.paddingY": 34,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-bubble-os-warning",
		name: "系统警示弹窗",
		category: "bubble",
		categoryNameZh: "气泡",
		previewText: "⚠️Warning",
		isPro: true,
		previewStyle: {
			color: "#7f1d1d",
			background: "#fee2e2",
			border: "1.5px solid #ef4444",
			borderRadius: "4px",
			fontWeight: 900,
			padding: "2px 8px",
		},
		tags: ["弹窗", "警告", "系统", "趣味", "警示"],
		params: {
			content: "⚠️ 系统提示：今日可爱指标已超标！",
			fontSize: 16,
			fontFamily: "Arial",
			color: "#7f1d1d",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#fee2e2",
			"background.cornerRadius": 6,
			"background.paddingX": 26,
			"background.paddingY": 34,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-bubble-sticky-note",
		name: "便利贴备忘录",
		category: "bubble",
		categoryNameZh: "气泡",
		previewText: "📝 Note",
		isPro: true,
		previewStyle: {
			color: "#713f12",
			background: "#fef08a",
			boxShadow: "2px 3px 6px rgba(0,0,0,0.3)",
			fontWeight: "bold",
			padding: "2px 8px",
		},
		tags: ["便利贴", "备忘录", "便签", "黄色", "笔记"],
		params: {
			content: "📝 备忘提醒：今天也要元气满满！",
			fontSize: 16,
			fontFamily: "Arial",
			color: "#713f12",
			textAlign: "left",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#fef08a",
			"background.cornerRadius": 2,
			"background.paddingX": 26,
			"background.paddingY": 34,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-bubble-sci-fi-hud",
		name: "赛博战术HUD框",
		category: "bubble",
		categoryNameZh: "气泡",
		previewText: "[TARGET]",
		isPro: true,
		previewStyle: {
			color: "#38bdf8",
			background: "rgba(3, 105, 161, 0.2)",
			border: "1.5px solid #0284c7",
			fontFamily: "monospace",
			fontWeight: "bold",
			padding: "2px 8px",
		},
		tags: ["HUD", "机甲", "科幻", "战术", "目标", "蓝色"],
		params: {
			content: "[TARGET LOCKED // 能量核心已锁定 98.4%]",
			fontSize: 15,
			fontFamily: "Courier New",
			color: "#38bdf8",
			textAlign: "left",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1.5,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "rgba(3, 105, 161, 0.3)",
			"background.cornerRadius": 0,
			"background.paddingX": 26,
			"background.paddingY": 34,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},

	// ==========================================
	// 7. 🎬 电影标题与片头 (Cinematic Titles)
	// ==========================================
	{
		id: "capcut-title-epic-cinema",
		name: "巨幕史诗片头",
		category: "title",
		categoryNameZh: "标题",
		previewText: "C I N E M A",
		isPro: true,
		previewStyle: {
			color: "#ffffff",
			letterSpacing: "6px",
			fontWeight: 300,
			textShadow: "0 2px 14px rgba(0,0,0,0.95)",
		},
		tags: ["电影", "大片", "史诗", "片头", "留白"],
		params: {
			content: "C I N E M A T I C",
			fontSize: 22,
			fontFamily: "Arial",
			color: "#ffffff",
			textAlign: "center",
			fontWeight: "normal",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 5,
			lineHeight: 1.3,
			"background.enabled": false,
			"background.color": "#000000",
			"background.cornerRadius": 0,
			"background.paddingX": 30,
			"background.paddingY": 40,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-title-documentary",
		name: "硬核纪录片大标",
		category: "title",
		categoryNameZh: "标题",
		previewText: "CHRONICLE",
		isPro: true,
		previewStyle: {
			color: "#f5f5f5",
			fontWeight: 900,
			letterSpacing: "3px",
			textShadow: "0 4px 16px rgba(0,0,0,0.95)",
		},
		tags: ["纪录片", "硬核", "重磅", "历史"],
		params: {
			content: "THE UNTOLD STORY 纪实风暴",
			fontSize: 24,
			fontFamily: "Arial Black",
			color: "#f5f5f5",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 3,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "rgba(0,0,0,0.75)",
			"background.cornerRadius": 4,
			"background.paddingX": 36,
			"background.paddingY": 48,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-title-scifi-interstellar",
		name: "星际科幻巨制",
		category: "title",
		categoryNameZh: "标题",
		previewText: "ODYSSEY",
		isPro: true,
		previewStyle: {
			color: "#e0f2fe",
			letterSpacing: "5px",
			fontWeight: 900,
			textShadow: "0 0 12px #38bdf8, 0 0 24px #0369a1",
		},
		tags: ["星际", "科幻", "太空", "巨制", "未来", "电影"],
		params: {
			content: "INTERSTELLAR ODYSSEY // 星际漫游",
			fontSize: 22,
			fontFamily: "Arial Black",
			color: "#e0f2fe",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 4,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "rgba(3, 15, 38, 0.8)",
			"background.cornerRadius": 4,
			"background.paddingX": 36,
			"background.paddingY": 46,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-title-vintage-classic",
		name: "1920s金边经典",
		category: "title",
		categoryNameZh: "标题",
		previewText: "GATSBY",
		isPro: true,
		previewStyle: {
			color: "#fef08a",
			fontFamily: "Georgia, serif",
			letterSpacing: "4px",
			border: "1px solid #ca8a04",
			padding: "2px 10px",
			textShadow: "0 2px 6px rgba(0,0,0,0.9)",
		},
		tags: ["复古", "老电影", "盖茨比", "金色", "优雅", "经典"],
		params: {
			content: "THE GOLDEN ERA · 黄金时代",
			fontSize: 20,
			fontFamily: "Georgia",
			color: "#fef08a",
			textAlign: "center",
			fontWeight: "normal",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 4,
			lineHeight: 1.3,
			"background.enabled": true,
			"background.color": "#1c1917",
			"background.cornerRadius": 0,
			"background.paddingX": 32,
			"background.paddingY": 42,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-title-thriller-mystery",
		name: "悬疑惊悚暗夜",
		category: "title",
		categoryNameZh: "标题",
		previewText: "SHADOWS",
		isPro: true,
		previewStyle: {
			color: "#cbd5e1",
			letterSpacing: "6px",
			fontWeight: 300,
			textShadow: "0 0 8px rgba(255,255,255,0.4), 0 4px 20px rgba(0,0,0,0.95)",
		},
		tags: ["悬疑", "惊悚", "暗夜", "阴影", "神秘", "电影"],
		params: {
			content: "SHADOWS IN THE DARK · 迷雾重重",
			fontSize: 20,
			fontFamily: "Arial",
			color: "#cbd5e1",
			textAlign: "center",
			fontWeight: "normal",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 4,
			lineHeight: 1.3,
			"background.enabled": false,
			"background.color": "#000000",
			"background.cornerRadius": 0,
			"background.paddingX": 28,
			"background.paddingY": 38,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-title-hk-wong-style",
		name: "王家卫复古港风",
		category: "title",
		categoryNameZh: "标题",
		previewText: "花樣年華",
		isPro: true,
		previewStyle: {
			color: "#dc2626",
			background: "#09090b",
			border: "1px solid #7f1d1d",
			fontWeight: 900,
			padding: "2px 8px",
			letterSpacing: "4px",
		},
		tags: ["港风", "复古", "王家卫", "电影", "胶片", "文艺"],
		params: {
			content: "花樣年華 · 記憶碎片",
			fontSize: 22,
			fontFamily: "Georgia",
			color: "#dc2626",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 4,
			lineHeight: 1.3,
			"background.enabled": true,
			"background.color": "#09090b",
			"background.cornerRadius": 2,
			"background.paddingX": 32,
			"background.paddingY": 44,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-title-trailer-teaser",
		name: "重磅预告TEASER",
		category: "title",
		categoryNameZh: "标题",
		previewText: "COMING SOON",
		isPro: true,
		previewStyle: {
			color: "#ffffff",
			background: "#b91c1c",
			fontWeight: 900,
			padding: "2px 10px",
			borderRadius: "4px",
			boxShadow: "0 0 16px rgba(185,28,28,0.8)",
			letterSpacing: "2px",
		},
		tags: ["预告片", "即将上映", "震撼", "重磅", "电影"],
		params: {
			content: "COMING SOON // 全球震撼上映",
			fontSize: 22,
			fontFamily: "Arial Black",
			color: "#ffffff",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 3,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#b91c1c",
			"background.cornerRadius": 4,
			"background.paddingX": 34,
			"background.paddingY": 44,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},

	// ==========================================
	// 8. 🌟 新增热门短视频与社交媒体精选模板
	// ==========================================
	{
		id: "capcut-hot-secret-reveal",
		name: "绝密大揭秘",
		category: "variety",
		categoryNameZh: "综艺",
		previewText: "TOP SECRET",
		isPro: false,
		previewStyle: {
			color: "#000000",
			background: "linear-gradient(90deg, #facc15 0%, #eab308 100%)",
			fontWeight: 900,
			padding: "2px 8px",
			border: "2px solid #000000",
			boxShadow: "3px 3px 0 #000000",
			letterSpacing: "1px",
		},
		tags: ["揭秘", "绝密", "爆款", "黄黑", "警示", "综艺"],
		params: {
			content: "⚠️ TOP SECRET // 独家绝密内幕",
			fontSize: 22,
			fontFamily: "Arial Black",
			color: "#000000",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1,
			lineHeight: 1.1,
			"background.enabled": true,
			"background.color": "#facc15",
			"background.cornerRadius": 4,
			"background.paddingX": 30,
			"background.paddingY": 40,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-variety-juejuezi-macaron",
		name: "绝绝子马卡龙",
		category: "variety",
		categoryNameZh: "综艺",
		previewText: "绝绝子",
		isPro: false,
		previewStyle: {
			color: "#ffffff",
			background: "linear-gradient(135deg, #f472b6 0%, #38bdf8 100%)",
			fontWeight: 900,
			padding: "2px 10px",
			borderRadius: "16px",
			textShadow: "0 2px 4px rgba(0,0,0,0.2)",
			boxShadow: "0 4px 12px rgba(244,114,182,0.4)",
		},
		tags: ["绝绝子", "马卡龙", "粉蓝", "可爱", "爆款", "潮流"],
		params: {
			content: "✨ 太赞了！真的绝绝子 ✨",
			fontSize: 22,
			fontFamily: "Arial",
			color: "#ffffff",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 2,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#f472b6",
			"background.cornerRadius": 16,
			"background.paddingX": 32,
			"background.paddingY": 42,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-variety-avoid-pitfall",
		name: "防坑避雷指南",
		category: "variety",
		categoryNameZh: "综艺",
		previewText: "避坑指南",
		isPro: false,
		previewStyle: {
			color: "#ef4444",
			background: "#fee2e2",
			fontWeight: 900,
			padding: "2px 8px",
			border: "1.5px dashed #ef4444",
			borderRadius: "6px",
		},
		tags: ["避坑", "防坑", "避雷", "测评", "干货", "实用"],
		params: {
			content: "🚫 新手必看！避坑防踩雷指南",
			fontSize: 21,
			fontFamily: "Arial Black",
			color: "#ef4444",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#ffffff",
			"background.cornerRadius": 6,
			"background.paddingX": 28,
			"background.paddingY": 38,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-variety-super-discount",
		name: "超值爆款推荐",
		category: "variety",
		categoryNameZh: "综艺",
		previewText: "超值推荐",
		isPro: false,
		previewStyle: {
			color: "#ffffff",
			background: "linear-gradient(135deg, #ea580c 0%, #dc2626 100%)",
			fontWeight: 900,
			padding: "2px 8px",
			borderRadius: "4px",
			boxShadow: "0 3px 6px rgba(220,38,38,0.4)",
		},
		tags: ["推荐", "爆款", "优惠", "买它", "购物", "带货"],
		params: {
			content: "🔥 必买爆款！年度超值好物推荐",
			fontSize: 22,
			fontFamily: "Arial Black",
			color: "#ffffff",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#dc2626",
			"background.cornerRadius": 6,
			"background.paddingX": 30,
			"background.paddingY": 40,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},

	// ==========================================
	// 9. 🎨 东方国风与水墨雅致艺术字
	// ==========================================
	{
		id: "capcut-art-ink-blue-china",
		name: "墨染青花",
		category: "art",
		categoryNameZh: "艺术",
		previewText: "青花墨韻",
		isPro: true,
		previewStyle: {
			color: "#1e3a8a",
			background: "linear-gradient(180deg, #f8fafc 0%, #e2e8f0 100%)",
			border: "1px solid #3b82f6",
			fontWeight: 700,
			padding: "2px 10px",
			letterSpacing: "4px",
			textShadow: "0 1px 2px rgba(30,58,138,0.2)",
		},
		tags: ["青花瓷", "水墨", "国风", "书法", "优雅", "古典"],
		params: {
			content: "青花墨韻 · 歲月流芳",
			fontSize: 22,
			fontFamily: "Georgia",
			color: "#1e3a8a",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 4,
			lineHeight: 1.3,
			"background.enabled": true,
			"background.color": "#f8fafc",
			"background.cornerRadius": 2,
			"background.paddingX": 32,
			"background.paddingY": 42,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-art-dunhuang-gold",
		name: "敦煌金碧飞天",
		category: "art",
		categoryNameZh: "艺术",
		previewText: "敦煌飛天",
		isPro: true,
		previewStyle: {
			color: "#d97706",
			background: "#1c1917",
			border: "1px solid #b45309",
			fontWeight: 800,
			padding: "2px 10px",
			letterSpacing: "3px",
			textShadow: "0 0 10px rgba(217,119,6,0.6)",
		},
		tags: ["敦煌", "飞天", "壁画", "矿物金", "国潮", "历史"],
		params: {
			content: "敦煌夢境 · 絲路梵音",
			fontSize: 22,
			fontFamily: "Georgia",
			color: "#f59e0b",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 3,
			lineHeight: 1.3,
			"background.enabled": true,
			"background.color": "#1c1917",
			"background.cornerRadius": 0,
			"background.paddingX": 34,
			"background.paddingY": 44,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-art-song-minimal-zen",
		name: "宋式极简淡雅",
		category: "art",
		categoryNameZh: "艺术",
		previewText: "浮生若夢",
		isPro: false,
		previewStyle: {
			color: "#52525b",
			fontWeight: 300,
			letterSpacing: "6px",
			padding: "2px 6px",
			borderBottom: "1px solid #a1a1aa",
		},
		tags: ["宋风", "极简", "淡雅", "禅意", "文艺", "清冷"],
		params: {
			content: "浮生若夢 · 靜水流深",
			fontSize: 20,
			fontFamily: "Georgia",
			color: "#71717a",
			textAlign: "center",
			fontWeight: "normal",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 6,
			lineHeight: 1.4,
			"background.enabled": false,
			"background.color": "#000000",
			"background.cornerRadius": 0,
			"background.paddingX": 26,
			"background.paddingY": 36,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},

	// ==========================================
	// 10. ✨ 潮流 Vlog、穿搭与生活方式
	// ==========================================
	{
		id: "capcut-vlog-daily-polaroid",
		name: "胶片碎片日常",
		category: "vlog",
		categoryNameZh: "Vlog",
		previewText: "DAILY VLOG",
		isPro: false,
		previewStyle: {
			color: "#0f172a",
			background: "#ffffff",
			fontWeight: 800,
			padding: "3px 10px",
			borderRadius: "2px",
			boxShadow: "0 2px 8px rgba(0,0,0,0.15)",
			letterSpacing: "2px",
		},
		tags: ["日常", "胶片", "拍立得", "vlog", "碎片", "记录"],
		params: {
			content: "DAILY VLOG // 慢调生活碎片记录",
			fontSize: 20,
			fontFamily: "Arial",
			color: "#0f172a",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 2,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#ffffff",
			"background.cornerRadius": 2,
			"background.paddingX": 30,
			"background.paddingY": 40,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-vlog-weekend-lemon",
		name: "周末放风柠檬黄",
		category: "vlog",
		categoryNameZh: "Vlog",
		previewText: "WEEKEND",
		isPro: false,
		previewStyle: {
			color: "#000000",
			background: "#fde047",
			fontWeight: 900,
			padding: "2px 8px",
			borderRadius: "4px",
			letterSpacing: "1px",
		},
		tags: ["周末", "放风", "柠檬黄", "活力", "出游", "旅行"],
		params: {
			content: "WEEKEND MOOD · 周末快乐放风中",
			fontSize: 21,
			fontFamily: "Arial Black",
			color: "#000000",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 1,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#fde047",
			"background.cornerRadius": 4,
			"background.paddingX": 28,
			"background.paddingY": 38,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-vlog-ootd-editorial",
		name: "OOTD 杂志排版",
		category: "vlog",
		categoryNameZh: "Vlog",
		previewText: "OOTD LOOK",
		isPro: false,
		previewStyle: {
			color: "#ffffff",
			background: "#18181b",
			border: "1px solid #3f3f46",
			fontWeight: 600,
			padding: "2px 10px",
			letterSpacing: "3px",
		},
		tags: ["穿搭", "OOTD", "时尚", "杂志", "高级感", "日常"],
		params: {
			content: "OOTD / TODAY'S CASUAL LOOK 今日穿搭",
			fontSize: 19,
			fontFamily: "Arial",
			color: "#ffffff",
			textAlign: "center",
			fontWeight: "normal",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 3,
			lineHeight: 1.3,
			"background.enabled": true,
			"background.color": "#18181b",
			"background.cornerRadius": 0,
			"background.paddingX": 30,
			"background.paddingY": 40,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-vlog-grwm-oatmilk",
		name: "GRWM 燕麦奶茶",
		category: "vlog",
		categoryNameZh: "Vlog",
		previewText: "GRWM TIME",
		isPro: false,
		previewStyle: {
			color: "#78350f",
			background: "#fef3c7",
			fontWeight: 700,
			padding: "2px 10px",
			borderRadius: "8px",
			letterSpacing: "1px",
		},
		tags: ["护肤", "化妆", "GRWM", "奶茶色", "治愈", "生活"],
		params: {
			content: "GRWM · 跟我一起沉浸式准备吧",
			fontSize: 20,
			fontFamily: "Georgia",
			color: "#78350f",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 2,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#fef3c7",
			"background.cornerRadius": 8,
			"background.paddingX": 28,
			"background.paddingY": 38,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-vlog-night-talk-aurora",
		name: "深夜电台极光",
		category: "vlog",
		categoryNameZh: "Vlog",
		previewText: "NIGHT TALK",
		isPro: true,
		previewStyle: {
			color: "#e0e7ff",
			background: "linear-gradient(90deg, #312e81 0%, #4c1d95 100%)",
			fontWeight: 700,
			padding: "2px 10px",
			borderRadius: "12px",
			boxShadow: "0 0 14px rgba(79,70,229,0.5)",
			letterSpacing: "2px",
		},
		tags: ["深夜", "电台", "极光", "治愈", "听歌", "情感"],
		params: {
			content: "NIGHT TALK // 深夜心事电台 🌙",
			fontSize: 20,
			fontFamily: "Arial",
			color: "#e0e7ff",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 2,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#312e81",
			"background.cornerRadius": 12,
			"background.paddingX": 30,
			"background.paddingY": 40,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},

	// ==========================================
	// 11. ⚡ 炫酷 3D、未来赛博与霓虹发光
	// ==========================================
	{
		id: "capcut-neon-cyber-matrix-green",
		name: "赛博矩阵黑客绿",
		category: "neon",
		categoryNameZh: "发光",
		previewText: "CYBER MATRIX",
		isPro: true,
		previewStyle: {
			color: "#22c55e",
			background: "#052e16",
			border: "1px solid #16a34a",
			fontWeight: 900,
			padding: "2px 8px",
			letterSpacing: "2px",
			textShadow: "0 0 8px #22c55e, 0 0 16px rgba(34,197,94,0.6)",
		},
		tags: ["黑客", "矩阵", "荧光绿", "赛博朋克", "未来", "代码"],
		params: {
			content: "[ SYSTEM_ONLINE // 赛博骇客终端 ]",
			fontSize: 21,
			fontFamily: "Courier New",
			color: "#22c55e",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 2,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#052e16",
			"background.cornerRadius": 2,
			"background.paddingX": 32,
			"background.paddingY": 42,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-3d-liquid-chrome-silver",
		name: "水银液态流体",
		category: "3d",
		categoryNameZh: "3D",
		previewText: "CHROME",
		isPro: true,
		previewStyle: {
			color: "#f8fafc",
			background: "linear-gradient(180deg, #94a3b8 0%, #334155 100%)",
			fontWeight: 900,
			padding: "2px 10px",
			borderRadius: "6px",
			textShadow: "0 2px 0 #1e293b, 0 4px 10px rgba(0,0,0,0.8)",
			boxShadow: "inset 0 1px 1px rgba(255,255,255,0.8)",
		},
		tags: ["金属", "水银", "液态", "银色", "高光", "未来感"],
		params: {
			content: "LIQUID CHROME // 流体金属光泽",
			fontSize: 22,
			fontFamily: "Arial Black",
			color: "#f8fafc",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 2,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#334155",
			"background.cornerRadius": 6,
			"background.paddingX": 32,
			"background.paddingY": 42,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-neon-vaporwave-retro-80s",
		name: "80s 蒸汽波合成器",
		category: "neon",
		categoryNameZh: "发光",
		previewText: "VAPORWAVE",
		isPro: true,
		previewStyle: {
			color: "#f472b6",
			background: "#1e1b4b",
			border: "1.5px solid #06b6d4",
			fontWeight: 900,
			padding: "2px 8px",
			textShadow: "0 0 8px #f472b6, 0 0 16px #06b6d4",
			letterSpacing: "2px",
		},
		tags: ["蒸汽波", "复古", "80年代", "霓虹", "粉蓝", "合成波"],
		params: {
			content: "✦ V A P O R W A V E 1 9 8 4 ✦",
			fontSize: 21,
			fontFamily: "Arial Black",
			color: "#f472b6",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 3,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#1e1b4b",
			"background.cornerRadius": 4,
			"background.paddingX": 34,
			"background.paddingY": 44,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-3d-lava-magma-burst",
		name: "熔岩炽热裂变",
		category: "3d",
		categoryNameZh: "3D",
		previewText: "LAVA BURST",
		isPro: true,
		previewStyle: {
			color: "#ffffff",
			background: "linear-gradient(180deg, #f97316 0%, #b91c1c 100%)",
			fontWeight: 900,
			padding: "2px 8px",
			borderRadius: "4px",
			textShadow: "0 2px 0 #7f1d1d, 0 0 12px #ea580c",
			boxShadow: "0 4px 12px rgba(234,88,12,0.6)",
		},
		tags: ["熔岩", "燃烧", "火焰", "炽热", "能量", "游戏"],
		params: {
			content: "⚡ LAVA ENERGY // 炽热能量全开",
			fontSize: 22,
			fontFamily: "Arial Black",
			color: "#ffffff",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 2,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#b91c1c",
			"background.cornerRadius": 4,
			"background.paddingX": 32,
			"background.paddingY": 42,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},

	// ==========================================
	// 12. 🎬 史诗大片与高口碑电影标题
	// ==========================================
	{
		id: "capcut-title-documentary-voice",
		name: "人文纪录片之声",
		category: "title",
		categoryNameZh: "标题",
		previewText: "DISCOVERY",
		isPro: false,
		previewStyle: {
			color: "#e2e8f0",
			fontWeight: 400,
			letterSpacing: "8px",
			textShadow: "0 2px 10px rgba(0,0,0,0.9)",
		},
		tags: ["纪录片", "国家地理", "探索", "自然", "人文", "大片"],
		params: {
			content: "VOICES OF THE EARTH · 大地之声",
			fontSize: 20,
			fontFamily: "Georgia",
			color: "#e2e8f0",
			textAlign: "center",
			fontWeight: "normal",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 6,
			lineHeight: 1.4,
			"background.enabled": false,
			"background.color": "#000000",
			"background.cornerRadius": 0,
			"background.paddingX": 30,
			"background.paddingY": 40,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-title-epic-fantasy-saga",
		name: "中世纪史诗传奇",
		category: "title",
		categoryNameZh: "标题",
		previewText: "THE CHRONICLES",
		isPro: true,
		previewStyle: {
			color: "#fde68a",
			background: "#18181b",
			border: "1px solid #78350f",
			fontWeight: 700,
			padding: "2px 12px",
			letterSpacing: "4px",
			textShadow: "0 0 10px rgba(245,158,11,0.5)",
		},
		tags: ["史诗", "魔幻", "传奇", "权力的游戏", "金色", "电影"],
		params: {
			content: "THE CHRONICLES OF LEGENDS · 英雄传奇",
			fontSize: 21,
			fontFamily: "Georgia",
			color: "#fde68a",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 4,
			lineHeight: 1.3,
			"background.enabled": true,
			"background.color": "#18181b",
			"background.cornerRadius": 0,
			"background.paddingX": 36,
			"background.paddingY": 46,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-title-scifi-year-2099",
		name: "未来纪元2099",
		category: "title",
		categoryNameZh: "标题",
		previewText: "YEAR 2099",
		isPro: true,
		previewStyle: {
			color: "#38bdf8",
			background: "#082f49",
			border: "1px solid #0284c7",
			fontWeight: 900,
			padding: "2px 10px",
			letterSpacing: "4px",
			textShadow: "0 0 8px #38bdf8",
		},
		tags: ["硬科幻", "星际", "未来", "2099", "蓝光", "太空"],
		params: {
			content: "PROJECT 2099 // 深空探索计划",
			fontSize: 22,
			fontFamily: "Arial Black",
			color: "#38bdf8",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "normal",
			textDecoration: "none",
			letterSpacing: 4,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#082f49",
			"background.cornerRadius": 2,
			"background.paddingX": 34,
			"background.paddingY": 44,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
	{
		id: "capcut-title-speed-racer",
		name: "极速狂飙动感字幕",
		category: "title",
		categoryNameZh: "标题",
		previewText: "MAX SPEED",
		isPro: false,
		previewStyle: {
			color: "#ffffff",
			background: "linear-gradient(90deg, #dc2626 0%, #f97316 100%)",
			fontWeight: 900,
			fontStyle: "italic",
			padding: "2px 10px",
			borderRadius: "2px",
			boxShadow: "0 4px 10px rgba(220,38,38,0.5)",
			letterSpacing: "2px",
		},
		tags: ["赛车", "极速", "动感", "斜体", "热血", "运动"],
		params: {
			content: "MAX SPEED // 突破极速极限",
			fontSize: 22,
			fontFamily: "Arial Black",
			color: "#ffffff",
			textAlign: "center",
			fontWeight: "bold",
			fontStyle: "italic",
			textDecoration: "none",
			letterSpacing: 2,
			lineHeight: 1.2,
			"background.enabled": true,
			"background.color": "#dc2626",
			"background.cornerRadius": 2,
			"background.paddingX": 32,
			"background.paddingY": 42,
			"background.offsetX": 0,
			"background.offsetY": 0,
		},
	},
];
