import type { TextAnimationPreset } from "./types";

export const TEXT_ANIMATION_IN_PRESETS: TextAnimationPreset[] = [
	// CapCut Editorial Presets (Apple Keynote / Fashion film look)
	{
		id: "whisperFade",
		name: "细语淡入",
		category: "in",
		icon: "✨",
		description: "微幅沉降+平滑淡入 (Keynote极简风)",
		defaultDuration: 0.6,
		easing: "power2.out",
	},
	{
		id: "riseSettle",
		name: "升起定格",
		category: "in",
		icon: "🛫",
		description: "自下而上柔和升起并平滑定格",
		defaultDuration: 0.6,
		easing: "power3.out",
	},
	{
		id: "stackReveal",
		name: "遮罩展开",
		category: "in",
		icon: "📑",
		description: "从基准线遮罩向上展开",
		defaultDuration: 0.5,
		easing: "power2.out",
	},
	{
		id: "letterCascade",
		name: "字母逐落",
		category: "in",
		icon: "💧",
		description: "字符轻快逐级下落",
		defaultDuration: 0.7,
		easing: "back.out",
	},
	{
		id: "maskWipeUp",
		name: "底部划出",
		category: "in",
		icon: "⬆️",
		description: "底部向上裁切划出 (社论杂志风)",
		defaultDuration: 0.5,
		easing: "power3.out",
	},
	{
		id: "splitLine",
		name: "双向合拢",
		category: "in",
		icon: "👐",
		description: "两侧聚拢交汇合一",
		defaultDuration: 0.6,
		easing: "power2.out",
	},
	{
		id: "weightShift",
		name: "间距收紧",
		category: "in",
		icon: "📐",
		description: "字距由宽至紧聚焦 (秀场风)",
		defaultDuration: 0.7,
		easing: "power2.out",
	},
	{
		id: "kineticPop",
		name: "动感快弹",
		category: "in",
		icon: "💥",
		description: "短促有力轻微回弹 (强调关键句)",
		defaultDuration: 0.4,
		easing: "back.out",
	},
	{
		id: "underlineSweep",
		name: "强调划入",
		category: "in",
		icon: "⚡",
		description: "随强调横线快速掠入",
		defaultDuration: 0.5,
		easing: "power3.out",
	},
	{
		id: "lowerThird",
		name: "信息条入",
		category: "in",
		icon: "🏷️",
		description: "左侧平稳滑入驻留 (人物介绍条)",
		defaultDuration: 0.5,
		easing: "power3.out",
	},
	{
		id: "zoomOutStat",
		name: "巨数定格",
		category: "in",
		icon: "🎯",
		description: "特大尺寸快速收拢定格 (数据展示)",
		defaultDuration: 0.6,
		easing: "power2.out",
	},
	// Classic In Presets
	{
		id: "typewriter",
		name: "打字机",
		category: "in",
		icon: "⌨️",
		description: "字符逐字浮现跳出",
		defaultDuration: 0.8,
		easing: "linear",
	},
	{
		id: "bounceIn",
		name: "弹跳放大",
		category: "in",
		icon: "🏀",
		description: "生动回弹放大进入",
		defaultDuration: 0.6,
		easing: "back.out",
	},
	{
		id: "zoomIn",
		name: "缩放淡入",
		category: "in",
		icon: "🔍",
		description: "由小至大平滑浮现",
		defaultDuration: 0.5,
		easing: "power2.out",
	},
	{
		id: "slideUp",
		name: "向上滑入",
		category: "in",
		icon: "🔼",
		description: "从底部向上滑入减速",
		defaultDuration: 0.5,
		easing: "power3.out",
	},
	{
		id: "slideDown",
		name: "向下滑入",
		category: "in",
		icon: "🔽",
		description: "从顶部向下滑入减速",
		defaultDuration: 0.5,
		easing: "power3.out",
	},
	{
		id: "slideRight",
		name: "向右滑入",
		category: "in",
		icon: "⏩",
		description: "从左侧向右平滑滑入",
		defaultDuration: 0.5,
		easing: "power3.out",
	},
	{
		id: "slideLeft",
		name: "向左滑入",
		category: "in",
		icon: "⏪",
		description: "从右侧向左平滑滑入",
		defaultDuration: 0.5,
		easing: "power3.out",
	},
	{
		id: "flipIn",
		name: "翻转飞入",
		category: "in",
		icon: "🌀",
		description: "3D立体倾斜翻转进入",
		defaultDuration: 0.6,
		easing: "back.out",
	},
	{
		id: "waveIn",
		name: "波浪升起",
		category: "in",
		icon: "🌊",
		description: "波浪起伏弹性升起",
		defaultDuration: 0.7,
		easing: "sine.out",
	},
	{
		id: "blurIn",
		name: "迷雾聚焦",
		category: "in",
		icon: "🌫️",
		description: "从虚焦渐进至清晰聚焦",
		defaultDuration: 0.6,
		easing: "power2.out",
	},
	{
		id: "elasticIn",
		name: "果冻弹性",
		category: "in",
		icon: "🍮",
		description: "果冻般剧烈弹性拉伸",
		defaultDuration: 0.8,
		easing: "elastic.out",
	},
];

export const TEXT_ANIMATION_OUT_PRESETS: TextAnimationPreset[] = [
	{
		id: "fadeOut",
		name: "渐隐淡出",
		category: "out",
		icon: "💨",
		description: "平滑透明度淡出",
		defaultDuration: 0.4,
		easing: "power2.in",
	},
	{
		id: "zoomOut",
		name: "缩放飞出",
		category: "out",
		icon: "🔎",
		description: "快速向内缩小消失",
		defaultDuration: 0.4,
		easing: "back.in",
	},
	{
		id: "slideDownOut",
		name: "向下滑出",
		category: "out",
		icon: "⬇️",
		description: "向下掉落淡出",
		defaultDuration: 0.4,
		easing: "power3.in",
	},
	{
		id: "slideUpOut",
		name: "向上滑出",
		category: "out",
		icon: "⬆️",
		description: "向上升起淡出",
		defaultDuration: 0.4,
		easing: "power3.in",
	},
	{
		id: "slideLeftOut",
		name: "向左滑出",
		category: "out",
		icon: "⬅️",
		description: "向左飞出画面",
		defaultDuration: 0.4,
		easing: "power3.in",
	},
	{
		id: "slideRightOut",
		name: "向右滑出",
		category: "out",
		icon: "➡️",
		description: "向右飞出画面",
		defaultDuration: 0.4,
		easing: "power3.in",
	},
	{
		id: "typewriterErase",
		name: "打字擦除",
		category: "out",
		icon: "🔙",
		description: "从后往前逐字消除",
		defaultDuration: 0.6,
		easing: "linear",
	},
];

export const TEXT_ANIMATION_LOOP_PRESETS: TextAnimationPreset[] = [
	{
		id: "pulse",
		name: "呼吸脉冲",
		category: "loop",
		icon: "🫀",
		description: "周期性微幅缩放呼吸",
		defaultDuration: 1.5,
		easing: "sine.inOut",
	},
	{
		id: "float",
		name: "上下浮动",
		category: "loop",
		icon: "🎈",
		description: "轻柔上下漂浮波浪",
		defaultDuration: 2.0,
		easing: "sine.inOut",
	},
	{
		id: "shake",
		name: "综艺抖动",
		category: "loop",
		icon: "⚡",
		description: "高频短促震撼抖动",
		defaultDuration: 0.5,
		easing: "linear",
	},
	{
		id: "swing",
		name: "左右摇摆",
		category: "loop",
		icon: "🔔",
		description: "钟摆式角度摆动",
		defaultDuration: 1.8,
		easing: "sine.inOut",
	},
	{
		id: "shimmer",
		name: "微光闪烁",
		category: "loop",
		icon: "✨",
		description: "明暗交替呼吸闪耀",
		defaultDuration: 1.2,
		easing: "sine.inOut",
	},
];

export const ALL_TEXT_ANIMATION_PRESETS: TextAnimationPreset[] = [
	...TEXT_ANIMATION_IN_PRESETS,
	...TEXT_ANIMATION_OUT_PRESETS,
	...TEXT_ANIMATION_LOOP_PRESETS,
];

export function getAnimationPresetById(id: string): TextAnimationPreset | undefined {
	return ALL_TEXT_ANIMATION_PRESETS.find((p) => p.id === id);
}
