import type { TTSVoice, VoiceCategory } from "./types";

export const VOICE_CATEGORIES: { id: VoiceCategory; label: string; icon: string }[] = [
	{ id: "hot", label: "🔥 热门推荐", icon: "FireIcon" },
	{ id: "narrative", label: "🎬 影视解说", icon: "Film01Icon" },
	{ id: "female", label: "🌸 甜美女声", icon: "SparklesIcon" },
	{ id: "male", label: "👨 沉稳男声", icon: "UserIcon" },
	{ id: "dialect", label: "🗣️ 特色方言", icon: "ChatBubbleIcon" },
	{ id: "foreign", label: "🌐 多语外语", icon: "GlobeIcon" },
];

export const TTS_VOICES: TTSVoice[] = [
	// ==========================================
	// 1. 🔥 热门推荐
	// ==========================================
	{
		id: "zh-CN-XiaoxiaoNeural",
		name: "晓晓",
		gender: "Female",
		locale: "zh-CN",
		category: "hot",
		description: "温暖活泼，最受欢迎的女播音员",
		tags: ["多用途", "活泼", "日常", "短视频"],
		sampleText: "你好呀，很高兴遇见你！今天想要制作什么有趣的视频呢？",
	},
	{
		id: "zh-CN-YunxiNeural",
		name: "云希",
		gender: "Male",
		locale: "zh-CN",
		category: "hot",
		description: "阳光帅气，影视解说与短视频爆款男声",
		tags: ["解说爆款", "年轻", "活力", "热血"],
		sampleText: "注意看，眼前这个男人叫小帅，他正在经历一场不可思议的冒险！",
	},
	{
		id: "zh-CN-YunjianNeural",
		name: "云健",
		gender: "Male",
		locale: "zh-CN",
		category: "hot",
		description: "磁性稳重，纪录片与新闻影视解说",
		tags: ["影视解说", "沉稳", "纪录片", "质感"],
		sampleText: "岁月流转，大自然的奇迹在这片古老的土地上悄然绽放。",
	},
	{
		id: "zh-CN-XiaoyiNeural",
		name: "晓依",
		gender: "Female",
		locale: "zh-CN",
		category: "hot",
		description: "知性优雅，有声书与情感电台",
		tags: ["情感电台", "知性", "治愈", "有声书"],
		sampleText: "夜深了，愿这一缕温柔的声音，伴你进入甜美的梦乡。",
	},

	// ==========================================
	// 2. 🎬 影视解说 & 旁白
	// ==========================================
	{
		id: "zh-CN-YunyangNeural",
		name: "云扬",
		gender: "Male",
		locale: "zh-CN",
		category: "narrative",
		description: "专业播音腔，新闻资讯与重大事件旁白",
		tags: ["新闻", "专业", "权威", "正能量"],
		sampleText: "各位观众朋友大家好，欢迎收看今天的特别报道。",
	},
	{
		id: "zh-CN-YunfengNeural",
		name: "云枫",
		gender: "Male",
		locale: "zh-CN",
		category: "narrative",
		description: "深沉老道，历史评书与悬疑故事",
		tags: ["历史", "悬疑", "深沉", "故事感"],
		sampleText: "话说天下大势，分久必合，合久必分。这桩陈年旧案背后...",
	},
	{
		id: "zh-CN-YunzeNeural",
		name: "云泽",
		gender: "Male",
		locale: "zh-CN",
		category: "narrative",
		description: "温润如玉，纪录片与科普知识",
		tags: ["纪录片", "科普", "温和", "自然"],
		sampleText: "在茫茫宇宙中，地球犹如一粒悬浮在阳光下的微尘。",
	},
	{
		id: "zh-CN-XiaohanNeural",
		name: "晓涵",
		gender: "Female",
		locale: "zh-CN",
		category: "narrative",
		description: "清澈从容，故事叙述与人物传记",
		tags: ["故事", "从容", "传记", "典雅"],
		sampleText: "每个人的人生都是一本独特的书，记录着岁月的沉淀与芬芳。",
	},

	// ==========================================
	// 3. 🌸 甜美女声
	// ==========================================
	{
		id: "zh-CN-XiaomengNeural",
		name: "晓梦",
		gender: "Female",
		locale: "zh-CN",
		category: "female",
		description: "清新甜美，生活 Vlog 与恋爱日常",
		tags: ["甜美", "Vlog", "恋爱", "元气"],
		sampleText: "今天阳光超级好！快跟我一起打卡这家藏在巷子里的宝藏甜品店吧！",
	},
	{
		id: "zh-CN-XiaoxuanNeural",
		name: "晓萱",
		gender: "Female",
		locale: "zh-CN",
		category: "female",
		description: "娇柔轻快，二次元与萌宠日常",
		tags: ["二次元", "萌宠", "娇萌", "搞怪"],
		sampleText: "咪呜~小主人你终于回来啦，今天有没有给我带小鱼干呀？",
	},
	{
		id: "zh-CN-XiaoshuangNeural",
		name: "晓双",
		gender: "Female",
		locale: "zh-CN",
		category: "female",
		description: "童真可爱，儿童绘本与少儿科普",
		tags: ["童声", "绘本", "可爱", "少儿"],
		sampleText: "从前有一只可爱的小白兔，住在森林深处的小木屋里...",
	},
	{
		id: "zh-CN-XiaomoNeural",
		name: "晓墨",
		gender: "Female",
		locale: "zh-CN",
		category: "female",
		description: "文静内敛，诗歌散文与阅读推荐",
		tags: ["诗歌", "散文", "文艺", "清雅"],
		sampleText: "林徽因曾写道：你是爱，是暖，是希望，你是人间的四月天。",
	},

	// ==========================================
	// 4. 👨 沉稳男声
	// ==========================================
	{
		id: "zh-CN-YunhaoNeural",
		name: "云皓",
		gender: "Male",
		locale: "zh-CN",
		category: "male",
		description: "阳光青年，科技数码测评与带货",
		tags: ["数码测评", "年轻", "现代", "科技"],
		sampleText: "今天我们上手体验这台最新旗舰手机，它的影像系统究竟表现如何？",
	},
	{
		id: "zh-CN-YunyeNeural",
		name: "云野",
		gender: "Male",
		locale: "zh-CN",
		category: "male",
		description: "低沉磁性，深夜电台与豪迈霸气",
		tags: ["磁性", "低音", "霸气", "电台"],
		sampleText: "纵使前路漫漫，亦要无畏前行。听从你内心最真实的召唤。",
	},
	{
		id: "zh-CN-YunxiaNeural",
		name: "云夏",
		gender: "Male",
		locale: "zh-CN",
		category: "male",
		description: "轻松幽默，段子吐槽与搞笑短剧",
		tags: ["幽默", "搞笑", "段子", "轻松"],
		sampleText: "家人们谁懂啊！今天上班路上发生了一件让人哭笑不得的事...",
	},

	// ==========================================
	// 5. 🗣️ 特色方言
	// ==========================================
	{
		id: "zh-CN-liaoning-XiaobeiNeural",
		name: "晓北 (东北话)",
		gender: "Female",
		locale: "zh-CN-liaoning",
		category: "dialect",
		description: "地道东北口音，幽默热情接地气",
		tags: ["东北话", "热情", "幽默", "老铁"],
		sampleText: "哎呀妈呀老铁，今天这菜整得可太带劲了，必须整两口！",
	},
	{
		id: "zh-CN-shaanxi-XiaoniNeural",
		name: "晓妮 (陕西话)",
		gender: "Female",
		locale: "zh-CN-shaanxi",
		category: "dialect",
		description: "秦腔陕韵，地道西北关中风情",
		tags: ["陕西话", "关中", "西北", "豪爽"],
		sampleText: "吃饱咧咥美咧！咱老陕的油泼辣子biangbiang面，那叫一个美！",
	},
	{
		id: "zh-HK-HiuGaaiNeural",
		name: "晓佳 (粤语)",
		gender: "Female",
		locale: "zh-HK",
		category: "dialect",
		description: "经典港式粤语女声，自然流利",
		tags: ["粤语", "港风", "广东话", "地道"],
		sampleText: "大家好！今日同大家分享一間超級正嘅港式茶餐廳！",
	},
	{
		id: "zh-HK-WanLungNeural",
		name: "云龙 (粤语)",
		gender: "Male",
		locale: "zh-HK",
		category: "dialect",
		description: "港味电影男声，TVB电视剧质感",
		tags: ["粤语男声", "TVB", "港片", "成熟"],
		sampleText: "做人最緊要就係開心，发生这种事大家都不想的。",
	},
	{
		id: "zh-TW-HsiaoChenNeural",
		name: "晓臻 (台湾国语)",
		gender: "Female",
		locale: "zh-TW",
		category: "dialect",
		description: "温柔软萌，台剧小清新腔调",
		tags: ["台湾腔", "温柔", "小清新", "软萌"],
		sampleText: "欸！你今天真的超可爱的耶，要不要一起去喝杯珍珠奶茶？",
	},
	{
		id: "zh-TW-YunJheNeural",
		name: "云哲 (台湾国语)",
		gender: "Male",
		locale: "zh-TW",
		category: "dialect",
		description: "阳光暖男，偶像剧男主既视感",
		tags: ["台湾男声", "暖男", "偶像剧", "阳光"],
		sampleText: "没关系啦，慢慢来，不管发生什么我都会陪在你身边哦。",
	},

	// ==========================================
	// 6. 🌐 多语外语
	// ==========================================
	{
		id: "en-US-JennyNeural",
		name: "Jenny (美音女声)",
		gender: "Female",
		locale: "en-US",
		category: "foreign",
		description: "Standard American English, natural and energetic",
		tags: ["English", "American", "Natural", "Clear"],
		sampleText: "Welcome to OpenLVET, the next generation creative video editor for creators.",
	},
	{
		id: "en-US-GuyNeural",
		name: "Guy (美音男声)",
		gender: "Male",
		locale: "en-US",
		category: "foreign",
		description: "Friendly and professional American male voice",
		tags: ["English", "American", "Male", "Podcast"],
		sampleText: "Hey everyone! In this tutorial, we will learn how to create stunning video effects.",
	},
	{
		id: "en-GB-SoniaNeural",
		name: "Sonia (英音女声)",
		gender: "Female",
		locale: "en-GB",
		category: "foreign",
		description: "Sophisticated British English accent",
		tags: ["English", "British", "Elegant", "BBC"],
		sampleText: "A wonderful day to explore the beauty of cinematic video storytelling.",
	},
	{
		id: "ja-JP-NanamiNeural",
		name: "七海 Nanami (日语)",
		gender: "Female",
		locale: "ja-JP",
		category: "foreign",
		description: "Anime & modern Japanese female voice",
		tags: ["Japanese", "Anime", "Kawaii", "Vlog"],
		sampleText: "こんにちは！今日も素晴らしい動画を作りましょうね！",
	},
	{
		id: "ko-KR-SunHiNeural",
		name: "善熙 SunHi (韩语)",
		gender: "Female",
		locale: "ko-KR",
		category: "foreign",
		description: "Melodious Korean female voice, K-Drama feel",
		tags: ["Korean", "K-Drama", "Sweet", "Natural"],
		sampleText: "안녕하세요! 오늘의 특별한 브이로그를 시작해볼까요?",
	},
];
